// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForCreateAnswerValues implements pgx.CopyFromSource.
type iteratorForCreateAnswerValues struct {
	rows                 []CreateAnswerValuesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateAnswerValues) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateAnswerValues) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SubmissionID,
		r.rows[0].QuestionID,
		r.rows[0].Value,
	}, nil
}

func (r iteratorForCreateAnswerValues) Err() error {
	return nil
}

func (q *Queries) CreateAnswerValues(ctx context.Context, arg []CreateAnswerValuesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"answer_values"}, []string{"submission_id", "question_id", "value"}, &iteratorForCreateAnswerValues{rows: arg})
}
