// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type QuestionType string

const (
	QuestionTypeChoice QuestionType = "choice"
	QuestionTypeText   QuestionType = "text"
)

func (e *QuestionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuestionType(s)
	case string:
		*e = QuestionType(s)
	default:
		return fmt.Errorf("unsupported scan type for QuestionType: %T", src)
	}
	return nil
}

type NullQuestionType struct {
	QuestionType QuestionType `json:"question_type"`
	Valid        bool         `json:"valid"` // Valid is true if QuestionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuestionType) Scan(value interface{}) error {
	if value == nil {
		ns.QuestionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuestionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuestionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuestionType), nil
}

type SessionStatus string

const (
	SessionStatusClosed  SessionStatus = "closed"
	SessionStatusOpen    SessionStatus = "open"
	SessionStatusStarted SessionStatus = "started"
	SessionStatusEnded   SessionStatus = "ended"
)

func (e *SessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionStatus(s)
	case string:
		*e = SessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionStatus: %T", src)
	}
	return nil
}

type NullSessionStatus struct {
	SessionStatus SessionStatus `json:"session_status"`
	Valid         bool          `json:"valid"` // Valid is true if SessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionStatus), nil
}

type SubmissionStatus string

const (
	SubmissionStatusJoined    SubmissionStatus = "joined"
	SubmissionStatusEditable  SubmissionStatus = "editable"
	SubmissionStatusSubmitted SubmissionStatus = "submitted"
	SubmissionStatusGraded    SubmissionStatus = "graded"
)

func (e *SubmissionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubmissionStatus(s)
	case string:
		*e = SubmissionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubmissionStatus: %T", src)
	}
	return nil
}

type NullSubmissionStatus struct {
	SubmissionStatus SubmissionStatus `json:"submission_status"`
	Valid            bool             `json:"valid"` // Valid is true if SubmissionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubmissionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubmissionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubmissionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubmissionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubmissionStatus), nil
}

type UserRole string

const (
	UserRoleExaminer UserRole = "examiner"
	UserRoleExaminee UserRole = "examinee"
	UserRoleAdmin    UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Answer struct {
	SubmissionID uuid.UUID `json:"submission_id"`
	QuestionID   uuid.UUID `json:"question_id"`
	Grade        *int32    `json:"grade"`
}

type AnswerKey struct {
	Value      string    `json:"value"`
	QuestionID uuid.UUID `json:"-"`
}

type AnswerValue struct {
	Value        string    `json:"value"`
	SubmissionID uuid.UUID `json:"submission_id"`
	QuestionID   uuid.UUID `json:"question_id"`
}

type ChoiceQuestion struct {
	ID               uuid.UUID    `json:"-"`
	IsMultipleChoice bool         `json:"is_multiple_choice" mapstructure:"is_multiple_choice"`
	Type             QuestionType `json:"-"`
}

type Examinee struct {
	ID uuid.UUID `json:"id"`
}

type Examiner struct {
	ID uuid.UUID `json:"id"`
}

type Option struct {
	Value      string    `json:"value"`
	QuestionID uuid.UUID `json:"-"`
	ImageUrl   *string   `json:"image_url" mapstructure:"image_url"`
	CreatedAt  time.Time `json:"created_at"`
}

type Question struct {
	ID        uuid.UUID    `json:"id"`
	Text      string       `json:"text"`
	ImageUrl  *string      `json:"image_url" mapstructure:"image_url"`
	Type      QuestionType `json:"type"`
	CreatedAt time.Time    `json:"-"`
	ScriptID  uuid.UUID    `json:"-"`
}

type Script struct {
	ID             uuid.UUID `json:"id"`
	Title          string    `json:"title"`
	Heading        string    `json:"heading"`
	Description    string    `json:"description"`
	Locked         *bool     `json:"locked"`
	CreatedAt      time.Time `json:"created_at"`
	LastModifiedAt time.Time `json:"last_modified_at"`
	CreatorID      uuid.UUID `json:"creator_id"`
}

type Session struct {
	ID            uuid.UUID     `json:"id"`
	Title         string        `json:"title"`
	Status        SessionStatus `json:"status"`
	QuestionCount *int32        `json:"question_count"`
	StartedAt     *time.Time    `json:"started_at"`
	EndedAt       *time.Time    `json:"ended_at"`
	JoinCode      string        `json:"join_code"`
	CreatorID     uuid.UUID     `json:"creator_id"`
	ScriptID      uuid.UUID     `json:"script_id"`
}

type Submission struct {
	ID          uuid.UUID        `json:"id"`
	Grade       *int32           `json:"grade"`
	Status      SubmissionStatus `json:"status"`
	SubmittedAt *time.Time       `json:"submitted_at"`
	JoinedAt    time.Time        `json:"joined_at"`
	ExamineeID  uuid.UUID        `json:"examinee_id"`
	SessionID   uuid.UUID        `json:"session_id"`
}

type TextQuestion struct {
	ID          uuid.UUID    `json:"-"`
	IsShortText bool         `json:"is_short_text" mapstructure:"is_short_text"`
	Type        QuestionType `json:"-"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	PasswordHash string    `json:"password_hash"`
	Role         UserRole  `json:"role"`
}
