// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: proctoring.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const logProctorEvent = `-- name: LogProctorEvent :one
INSERT INTO proctor_events (
    session_id,
    examinee_id,
    type,
    occurred_at
) VALUES ($1, $2, $3, $4)
RETURNING id
`

type LogProctorEventParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
	Type       string    `json:"type"`
	OccurredAt time.Time `json:"occurred_at"`
}

func (q *Queries) LogProctorEvent(ctx context.Context, arg LogProctorEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, logProctorEvent,
		arg.SessionID,
		arg.ExamineeID,
		arg.Type,
		arg.OccurredAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
