// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Calculates the mark for a submission based on
	// the individual marks for each question's answer.
	//
	//-------------------------------------------------
	CalculateSubmisionMark(ctx context.Context, submissionID uuid.UUID) (int64, error)
	// Puts the session in CLOSED mode (default mode). While in
	// CLOSED mode, examinees cannot join the session. Only
	// sessions in OPEN mode can be closed.
	//---------------------------------------------------------
	CloseSession(ctx context.Context, id uuid.UUID) (Session, error)
	// Creates a new choice question
	//
	//------------------------------
	CreateChoiceQuestion(ctx context.Context, arg CreateChoiceQuestionParams) (uuid.UUID, error)
	CreateExaminee(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	CreateExaminer(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// Creates a new script
	//
	//---------------------
	CreateScript(ctx context.Context, arg CreateScriptParams) (Script, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (uuid.UUID, error)
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	// Creates a new text question
	//
	//----------------------------
	CreateTextQuestion(ctx context.Context, arg CreateTextQuestionParams) (uuid.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Deletes the question if possible.
	// cascades to child components (e.g. subquestions & options)
	//
	//-----------------------------------------------------------
	DeleteQuestion(ctx context.Context, id uuid.UUID) error
	// Deletes the script if possible
	//
	//-------------------------------
	DeleteScript(ctx context.Context, id uuid.UUID) error
	DeleteSessionByID(ctx context.Context, id uuid.UUID) error
	// Sets the session to ENDED mode. Only sessions in STARTED
	// mode can be started.
	//----------------------------------------------------------
	EndSession(ctx context.Context, id uuid.UUID) (Session, error)
	// Finds the answer key for a question as a list
	//
	//----------------------------------------------
	FindAnswerKeyForQuestion(ctx context.Context, questionID uuid.UUID) ([]string, error)
	FindChoiceQuestionByID(ctx context.Context, id uuid.UUID) (ChoiceQuestion, error)
	FindExamineeByEmail(ctx context.Context, email string) (User, error)
	FindExaminerByEmail(ctx context.Context, email string) (User, error)
	// Finds options for a question order by creation.
	// Used for obtaining options for a question for editing
	//
	//------------------------------------------------------
	FindOptionsForQuestion(ctx context.Context, questionID uuid.UUID) ([]Option, error)
	// Finds options for a question unordered. Used for
	// obtaining options for a question during an exam session
	//
	//--------------------------------------------------------
	FindOptionsForQuestionShuffled(ctx context.Context, questionID uuid.UUID) ([]Option, error)
	// Gets a single question
	//
	//-----------------------
	FindQuestionByID(ctx context.Context, id uuid.UUID) (Question, error)
	// Gets all the questions for a script ordered
	// by time of creation
	//
	//--------------------------------------------
	FindQuestionsForScript(ctx context.Context, id uuid.UUID) ([]Question, error)
	// Returns all question fields assigned for an examinee.
	// Combine with FindOptionsForQuestionShuffled
	//
	//------------------------------------------------------
	FindQuestionsForSubmission(ctx context.Context, submissionID uuid.UUID) ([]Question, error)
	// Finds a script by its ID
	//
	//-------------------------
	FindScriptByID(ctx context.Context, id uuid.UUID) (Script, error)
	// Finds the number of scripts belonging to the
	// examiner
	//
	// --------------------------------------------
	FindScriptCountForExaminer(ctx context.Context, creatorID uuid.UUID) (int64, error)
	//-----------------------------------
	FindScriptForSubmission(ctx context.Context, submissionID uuid.UUID) (Script, error)
	// Gets the scripts belonging to the examiner
	// with cursor pagination
	//
	//-------------------------------------------
	FindScriptsForExaminer(ctx context.Context, arg FindScriptsForExaminerParams) ([]Script, error)
	FindSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	FindSessionByJoinCode(ctx context.Context, joinCode string) (Session, error)
	//------------------------------------------------------------------------------
	//------------------------------------------------------------------------------
	FindSessionsForExaminer(ctx context.Context, creatorID uuid.UUID) ([]Session, error)
	// Gets the answers for a submission
	//
	//----------------------------------
	FindSubmissionAnswers(ctx context.Context, id uuid.UUID) ([]FindSubmissionAnswersRow, error)
	FindSubmissionByID(ctx context.Context, id uuid.UUID) (Submission, error)
	FindSubmissionsForSession(ctx context.Context, sessionID uuid.UUID) ([]Submission, error)
	FindTextQuestionByID(ctx context.Context, id uuid.UUID) (TextQuestion, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id uuid.UUID) (User, error)
	//------------------------------------------------------------------------------
	//- Changing Session Status ----------------------------------------------------
	//------------------------------------------------------------------------------
	//-----------------------------------------------------------------------
	// State machine :: (Start) : CLOSED <-> OPEN -> STARTED -> ENDED : (End)
	//-----------------------------------------------------------------------
	// Puts the session in OPEN mode. While in OPEN mode
	// examinees can join the session. Only sessions in
	// CLOSED mode can be opened.
	//--------------------------------------------------
	OpenSession(ctx context.Context, id uuid.UUID) (Session, error)
	// Fully replace all answer key values for the
	// question with the given ID
	//
	//--------------------------------------------
	ReplaceAnswerKeyForQuestion(ctx context.Context, arg ReplaceAnswerKeyForQuestionParams) error
	// Fully replace all options with arrays of new values.
	// Arrays passed are "zipped" together using unnest.
	// Will not work with other subquestion types thanks to the
	// foreign key constraints.
	//
	//---------------------------------------------------------
	ReplaceOptionsForQuestion(ctx context.Context, arg ReplaceOptionsForQuestionParams) error
	// Replaces the submission answer for a given question
	//
	//----------------------------------------------------
	ReplaceSubAnswerForQuestion(ctx context.Context, arg ReplaceSubAnswerForQuestionParams) error
	// Finds the number of scripts belonging to the
	// examiner with the search query
	//
	// --------------------------------------------
	SearchScriptCountForExaminer(ctx context.Context, arg SearchScriptCountForExaminerParams) (int64, error)
	// Gets the scripts belonging to the examiner
	// with cursor pagination and a search query
	//
	//-------------------------------------------
	SearchScriptsForExaminer(ctx context.Context, arg SearchScriptsForExaminerParams) ([]Script, error)
	// Sets the questions for the submission of a user. Intended to
	// be used after an examiner starts the exam session before
	// submissions are set as 'editable' for examinees to answer
	//
	//--------------------------------------------------------------
	SetQuestionsForSubmissions(ctx context.Context, sessionID uuid.UUID) error
	// Updates the mark for an answer to a question in
	// a submission. Can only update a submitted submission
	//
	//-----------------------------------------------------
	SetSubmissionQuestionMark(ctx context.Context, arg SetSubmissionQuestionMarkParams) (SubmissionQuestion, error)
	// Set submissions as editable. Intended to be used
	// when the session has been started and the questions
	// for each user's submission has been set
	//
	//----------------------------------------------------
	SetSubmissionsEditableForSession(ctx context.Context, sessionID uuid.UUID) error
	// Sets the session to STARTED mode. Only sessions in OPEN
	// mode can be started.
	//----------------------------------------------------------
	StartSession(ctx context.Context, id uuid.UUID) (StartSessionRow, error)
	// Submits submission for a given session. Intended to be
	// used by the server to auto lock examinee submissions
	// when the session ends. Once submitted, the submission
	// can not be edited again.
	//
	//-------------------------------------------------------
	SubmitAllSubmissionsForSession(ctx context.Context, sessionID uuid.UUID) error
	// Submits a single submission for an examinee. Intended to
	// be used by the examinee to submit their answers when done
	//
	//----------------------------------------------------------
	SubmitSubmission(ctx context.Context, arg SubmitSubmissionParams) (Submission, error)
	// Updates the parent question fields if possible.
	//
	//------------------------------------------------
	UpdateQuestionFields(ctx context.Context, arg UpdateQuestionFieldsParams) error
	// Updates the script if possible
	//
	//-------------------------------
	UpdateScriptFields(ctx context.Context, arg UpdateScriptFieldsParams) (uuid.UUID, error)
	//------------------------------------------------------------------------------
	//------------------------------------------------------------------------------
	UpdateSessionFields(ctx context.Context, arg UpdateSessionFieldsParams) (Session, error)
	// Insert text-question values unless there is conflict,
	// in which case update the existing subquestion.
	//
	// Inserting a new subquestion in this case will automatically
	// delete all other subquestions & change the type of the
	// parent question to maintain FK constraints.
	//
	//-------------------------------------------------------------
	UpsertChoiceQuestion(ctx context.Context, arg UpsertChoiceQuestionParams) error
	// Insert text-question values unless there is conflict,
	// in which case update the existing subquestion.
	//
	// Inserting a new subquestion in this case will automatically
	// delete all other subquestions & change the type of the
	// parent question to maintain FK constraints.
	//
	//-------------------------------------------------------------
	UpsertTextQuestion(ctx context.Context, arg UpsertTextQuestionParams) error
}

var _ Querier = (*Queries)(nil)
