// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Calculates the mark for a submission based on
	// the individual marks for each question's answer.
	//
	CalculateSubmisionMark(ctx context.Context, submissionID uuid.UUID) (int64, error)
	// Puts the session in CLOSED mode (default mode). While in
	// CLOSED mode, examinees cannot join the session. Only
	// sessions in OPEN mode can be closed.
	//
	CloseSession(ctx context.Context, id uuid.UUID) (Session, error)
	// Creates a new choice question
	//
	//------------------------------
	CreateChoiceQuestion(ctx context.Context, arg CreateChoiceQuestionParams) (uuid.UUID, error)
	CreateExaminee(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	CreateExaminer(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// Creates a new script
	//
	//---------------------
	CreateScript(ctx context.Context, arg CreateScriptParams) (Script, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (uuid.UUID, error)
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	// Creates a new text question
	//
	//----------------------------
	CreateTextQuestion(ctx context.Context, arg CreateTextQuestionParams) (uuid.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Deletes the question if possible.
	// cascades to child components (e.g. subquestions & options)
	//
	//-----------------------------------------------------------
	DeleteQuestion(ctx context.Context, id uuid.UUID) error
	// Deletes the script if possible
	//
	//-------------------------------
	DeleteScript(ctx context.Context, id uuid.UUID) error
	// Deletes a session only if it is CLOSED
	//
	DeleteSessionByID(ctx context.Context, id uuid.UUID) error
	// Sets the session to ENDED mode. Only sessions in STARTED
	// mode can be started.
	//
	EndSession(ctx context.Context, id uuid.UUID) (Session, error)
	// Finds the answer key for a question as a list
	//
	//----------------------------------------------
	FindAnswerKeyForQuestion(ctx context.Context, questionID uuid.UUID) ([]string, error)
	FindChoiceQuestionByID(ctx context.Context, id uuid.UUID) (ChoiceQuestion, error)
	// Returns the submission ID if the examinee may open a websocket connection.
	//
	// OPEN:     enrolled or left (waiting room entry / reconnect)
	// STARTED:  disconnected only (grace reconnect; flagged requires appeal first)
	//
	FindConnectableSubmission(ctx context.Context, arg FindConnectableSubmissionParams) (uuid.UUID, error)
	FindExamineeByEmail(ctx context.Context, email string) (User, error)
	FindExaminerByEmail(ctx context.Context, email string) (User, error)
	// Finds options for a question order by creation.
	// Used for obtaining options for a question for editing
	//
	//------------------------------------------------------
	FindOptionsForQuestion(ctx context.Context, questionID uuid.UUID) ([]Option, error)
	// Finds options for a question unordered. Used for
	// obtaining options for a question during an exam session
	//
	//--------------------------------------------------------
	FindOptionsForQuestionShuffled(ctx context.Context, questionID uuid.UUID) ([]Option, error)
	// Gets a single question
	//
	//-----------------------
	FindQuestionByID(ctx context.Context, id uuid.UUID) (Question, error)
	// Gets all the questions for a script ordered
	// by time of creation
	//
	//--------------------------------------------
	FindQuestionsForScript(ctx context.Context, id uuid.UUID) ([]Question, error)
	// Returns all question fields assigned for an examinee.
	// Combine with FindOptionsForQuestionShuffled
	//
	//------------------------------------------------------
	FindQuestionsForSubmission(ctx context.Context, submissionID uuid.UUID) ([]Question, error)
	// Finds a script by its ID
	//
	//-------------------------
	FindScriptByID(ctx context.Context, id uuid.UUID) (Script, error)
	// Finds the number of scripts belonging to the
	// examiner
	//
	// --------------------------------------------
	FindScriptCountForExaminer(ctx context.Context, creatorID uuid.UUID) (int64, error)
	//-----------------------------------
	FindScriptForSubmission(ctx context.Context, submissionID uuid.UUID) (Script, error)
	// Gets the scripts belonging to the examiner
	// with cursor pagination
	//
	//-------------------------------------------
	FindScriptsForExaminer(ctx context.Context, arg FindScriptsForExaminerParams) ([]Script, error)
	FindSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	FindSessionByJoinCode(ctx context.Context, joinCode string) (Session, error)
	FindSessionsForExaminer(ctx context.Context, creatorID uuid.UUID) ([]Session, error)
	// Gets the answers for a submission
	//
	FindSubmissionAnswers(ctx context.Context, id uuid.UUID) ([]FindSubmissionAnswersRow, error)
	FindSubmissionByID(ctx context.Context, id uuid.UUID) (Submission, error)
	FindSubmissionStatus(ctx context.Context, arg FindSubmissionStatusParams) (SubmissionStatus, error)
	FindSubmissionsForSession(ctx context.Context, sessionID uuid.UUID) ([]Submission, error)
	FindTextQuestionByID(ctx context.Context, id uuid.UUID) (TextQuestion, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id uuid.UUID) (User, error)
	LogProctorEvent(ctx context.Context, arg LogProctorEventParams) (uuid.UUID, error)
	// Puts the session in OPEN mode. While in OPEN mode
	// examinees can join the session. Only sessions in
	// CLOSED mode can be opened.
	//
	OpenSession(ctx context.Context, id uuid.UUID) (Session, error)
	// Fully replace all answer key values for the
	// question with the given ID
	//
	//--------------------------------------------
	ReplaceAnswerKeyForQuestion(ctx context.Context, arg ReplaceAnswerKeyForQuestionParams) error
	// Fully replace all options with arrays of new values.
	// Arrays passed are "zipped" together using unnest.
	// Will not work with other subquestion types thanks to the
	// foreign key constraints.
	//
	//---------------------------------------------------------
	ReplaceOptionsForQuestion(ctx context.Context, arg ReplaceOptionsForQuestionParams) error
	// Replaces the submission answer for a given question
	//
	ReplaceSubAnswerForQuestion(ctx context.Context, arg ReplaceSubAnswerForQuestionParams) error
	// Finds the number of scripts belonging to the
	// examiner with the search query
	//
	// --------------------------------------------
	SearchScriptCountForExaminer(ctx context.Context, arg SearchScriptCountForExaminerParams) (int64, error)
	// Gets the scripts belonging to the examiner
	// with cursor pagination and a search query
	//
	//-------------------------------------------
	SearchScriptsForExaminer(ctx context.Context, arg SearchScriptsForExaminerParams) ([]Script, error)
	// Sets the questions for the submission of a user. Intended to
	// be used after an examiner starts the exam session before
	// submissions are set as EDITABLE for examinees to answer
	//
	SetQuestionsForSubmissions(ctx context.Context, sessionID uuid.UUID) error
	// Disconnect during STARTED while still eligible to answer (EDITABLE -> DISCONNECTED).
	//
	SetSubmissionDisconnected(ctx context.Context, arg SetSubmissionDisconnectedParams) (Submission, error)
	// Examiner grants appeal and client is disconnected in
	// session hub (FLAGGED -> DISCONNECTED).
	//
	SetSubmissionDisconnectedFromFlagged(ctx context.Context, arg SetSubmissionDisconnectedFromFlaggedParams) (Submission, error)
	// Examiner readmit after missing the start window (LEFT -> DISCONNECTED).
	// Examinee reconnects with SetSubmissionEditableFromDisconnect.
	//
	SetSubmissionDisconnectedFromLeft(ctx context.Context, arg SetSubmissionDisconnectedFromLeftParams) (Submission, error)
	// Reconnect during STARTED after grace disconnect (DISCONNECTED -> EDITABLE).
	//
	SetSubmissionEditableFromDisconnect(ctx context.Context, arg SetSubmissionEditableFromDisconnectParams) (Submission, error)
	// Examiner grants appeal and client is connected in session
	// hub (FLAGGED -> EDITABLE).
	//
	SetSubmissionEditableFromFlagged(ctx context.Context, arg SetSubmissionEditableFromFlaggedParams) (Submission, error)
	// Flag submission when grace period has expired
	// (DISCONNECTED -> FLAGGED).
	//
	SetSubmissionFlaggedFromDisconnect(ctx context.Context, arg SetSubmissionFlaggedFromDisconnectParams) (Submission, error)
	// Flag submission when if server flags user as cheating
	// (EDITABLE -> FLAGGED).
	//
	SetSubmissionFlaggedFromEditable(ctx context.Context, arg SetSubmissionFlaggedFromEditableParams) (Submission, error)
	// Connect during OPEN: first entry (ENROLLED -> JOINED)
	// or reconnect (LEFT -> JOINED).
	//
	SetSubmissionJoined(ctx context.Context, arg SetSubmissionJoinedParams) (Submission, error)
	// Disconnect during OPEN (JOINED -> LEFT). Ensures session start does not
	// promote disconnected examinees to EDITABLE.
	//
	SetSubmissionLeft(ctx context.Context, arg SetSubmissionLeftParams) (Submission, error)
	// Set the submission status to a connected state based on current
	// submission and session state
	//
	// submission: (ENROLLED, LEFT) session: OPEN       -> JOINED
	// submission: (DISCONNECTED)   sesssion: STARTED   -> EDITABLE
	//
	SetSubmissionOnConnect(ctx context.Context, arg SetSubmissionOnConnectParams) (Submission, error)
	// Set the submission status to a disconnected state based
	// on current submission and session state
	//
	// submission: (JOINED)     session: OPEN       -> LEFT
	// submission: (EDITABLE)   sesssion: STARTED   -> DISCONNECTED
	//
	SetSubmissionOnDisconnect(ctx context.Context, arg SetSubmissionOnDisconnectParams) (Submission, error)
	// Updates the mark for an answer to a question in
	// a submission. Can only update a submitted submission
	//
	SetSubmissionQuestionMark(ctx context.Context, arg SetSubmissionQuestionMarkParams) (SubmissionQuestion, error)
	// On session start: promote waiting-room examinees and lock out no-shows.
	// Use after the session is STARTED and submission questions are assigned.
	//
	// ENROLLED -> LEFT: enrolled but never connected during OPEN (see SetSubmissionJoined).
	// JOINED -> EDITABLE: was in the waiting room when the exam started.
	//
	// Rows already LEFT (disconnected during OPEN) are unchanged and require
	// examiner readmit (SetSubmissionDisconnectedFromLeft) to participate.
	//
	SetSubmissionStatusesForStartedSession(ctx context.Context, sessionID uuid.UUID) (int64, error)
	// Voluntary final submit by the examinee (EDITABLE -> SUBMITTED).
	//
	SetSubmissionSubmitted(ctx context.Context, arg SetSubmissionSubmittedParams) (Submission, error)
	// Sets the session to STARTED mode. Only sessions in OPEN
	// mode can be started.
	//
	StartSession(ctx context.Context, id uuid.UUID) (StartSessionRow, error)
	// On session end: auto-submit all in-progress submissions for the session.
	// Updates LEFT, EDITABLE, DISCONNECTED, and FLAGGED to SUBMITTED.
	//
	// ENROLLED and JOINED are excluded (should not exist after session start;
	// see SetSubmissionStatusesForStartedSession). SUBMITTED and MARKED are terminal.
	//
	SubmitAllSubmissionsForSession(ctx context.Context, sessionID uuid.UUID) (int64, error)
	// Updates the parent question fields if possible.
	//
	//------------------------------------------------
	UpdateQuestionFields(ctx context.Context, arg UpdateQuestionFieldsParams) error
	// Updates the script if possible
	//
	//-------------------------------
	UpdateScriptFields(ctx context.Context, arg UpdateScriptFieldsParams) (uuid.UUID, error)
	// Updates the top level fields of the sessions
	//
	UpdateSessionFields(ctx context.Context, arg UpdateSessionFieldsParams) (Session, error)
	// Insert text-question values unless there is conflict,
	// in which case update the existing subquestion.
	//
	// Inserting a new subquestion in this case will automatically
	// delete all other subquestions & change the type of the
	// parent question to maintain FK constraints.
	//
	//-------------------------------------------------------------
	UpsertChoiceQuestion(ctx context.Context, arg UpsertChoiceQuestionParams) error
	// Insert text-question values unless there is conflict,
	// in which case update the existing subquestion.
	//
	// Inserting a new subquestion in this case will automatically
	// delete all other subquestions & change the type of the
	// parent question to maintain FK constraints.
	//
	//-------------------------------------------------------------
	UpsertTextQuestion(ctx context.Context, arg UpsertTextQuestionParams) error
}

var _ Querier = (*Queries)(nil)
