// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: questions.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createChoiceQuestion = `-- name: CreateChoiceQuestion :one

WITH inserted AS (
    INSERT INTO questions (
        script_id,
        type,
        text,
        image_url,
        mark
    ) SELECT $5::uuid, 'choice', $1, $2, $3 FROM scripts
    WHERE scripts.id = $5::uuid
        AND scripts.locked = false
    RETURNING id, text, image_url, type, mark, created_at, script_id
)
INSERT INTO choice_questions (
    id,
    is_multiple_choice
) SELECT inserted.id, $4 FROM
    inserted INNER JOIN scripts ON inserted.script_id = scripts.id
WHERE scripts.id = $5::uuid
AND scripts.locked = false
RETURNING id
`

type CreateChoiceQuestionParams struct {
	Text             string    `json:"text"`
	ImageUrl         *string   `json:"image_url" mapstructure:"image_url"`
	Mark             *int32    `json:"mark"`
	IsMultipleChoice bool      `json:"is_multiple_choice" mapstructure:"is_multiple_choice"`
	ScriptID         uuid.UUID `json:"script_id"`
}

// Creates a new choice question
func (q *Queries) CreateChoiceQuestion(ctx context.Context, arg CreateChoiceQuestionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createChoiceQuestion,
		arg.Text,
		arg.ImageUrl,
		arg.Mark,
		arg.IsMultipleChoice,
		arg.ScriptID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createTextQuestion = `-- name: CreateTextQuestion :one

WITH inserted AS (
    INSERT INTO questions (
        script_id,
        type,
        text,
        image_url,
        mark
    ) SELECT $5::uuid, 'text', $1, $2, $4 FROM scripts
    WHERE scripts.id = $5::uuid
        AND scripts.locked = false
    RETURNING id, text, image_url, type, mark, created_at, script_id
)
INSERT INTO text_questions (
    id,
    is_short_text
) SELECT inserted.id, $3 FROM
    inserted INNER JOIN scripts ON inserted.script_id = scripts.id
WHERE scripts.id = $5::uuid
AND scripts.locked = false
RETURNING id
`

type CreateTextQuestionParams struct {
	Text        string    `json:"text"`
	ImageUrl    *string   `json:"image_url" mapstructure:"image_url"`
	IsShortText bool      `json:"is_short_text" mapstructure:"is_short_text"`
	Mark        *int32    `json:"mark"`
	ScriptID    uuid.UUID `json:"script_id"`
}

// Creates a new text question
func (q *Queries) CreateTextQuestion(ctx context.Context, arg CreateTextQuestionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTextQuestion,
		arg.Text,
		arg.ImageUrl,
		arg.IsShortText,
		arg.Mark,
		arg.ScriptID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteQuestion = `-- name: DeleteQuestion :exec

DELETE FROM questions
USING scripts
WHERE questions.id = $1
    AND scripts.id = questions.script_id
    AND scripts.locked = false
`

// Deletes the question if possible.
// cascades to child components (e.g. subquestions & options)
func (q *Queries) DeleteQuestion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuestion, id)
	return err
}

const findAnswerKeyForQuestion = `-- name: FindAnswerKeyForQuestion :many

SELECT answer_keys.value FROM answer_keys
WHERE answer_keys.question_id = $1
`

// Finds the answer key for a question as a list
func (q *Queries) FindAnswerKeyForQuestion(ctx context.Context, questionID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, findAnswerKeyForQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var value string
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findChoiceQuestionByID = `-- name: FindChoiceQuestionByID :one

SELECT id, is_multiple_choice, type FROM choice_questions
WHERE choice_questions.id = $1
`

func (q *Queries) FindChoiceQuestionByID(ctx context.Context, id uuid.UUID) (ChoiceQuestion, error) {
	row := q.db.QueryRow(ctx, findChoiceQuestionByID, id)
	var i ChoiceQuestion
	err := row.Scan(&i.ID, &i.IsMultipleChoice, &i.Type)
	return i, err
}

const findOptionsForQuestion = `-- name: FindOptionsForQuestion :many
SELECT value, question_id, image_url, created_at FROM options
    WHERE options.question_id = $1
    ORDER BY options.created_at ASC
`

// Finds options for a question order by creation.
// Used for obtaining options for a question for editing
func (q *Queries) FindOptionsForQuestion(ctx context.Context, questionID uuid.UUID) ([]Option, error) {
	rows, err := q.db.Query(ctx, findOptionsForQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Option{}
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.Value,
			&i.QuestionID,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOptionsForQuestionShuffled = `-- name: FindOptionsForQuestionShuffled :many
SELECT value, question_id, image_url, created_at FROM options
    WHERE options.question_id = $1
    ORDER BY random()
`

// Finds options for a question unordered. Used for
// obtaining options for a question during an exam session
func (q *Queries) FindOptionsForQuestionShuffled(ctx context.Context, questionID uuid.UUID) ([]Option, error) {
	rows, err := q.db.Query(ctx, findOptionsForQuestionShuffled, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Option{}
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.Value,
			&i.QuestionID,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findQuestionByID = `-- name: FindQuestionByID :one

SELECT id, text, image_url, type, mark, created_at, script_id FROM questions
WHERE questions.id = $1
`

// Gets a single question
func (q *Queries) FindQuestionByID(ctx context.Context, id uuid.UUID) (Question, error) {
	row := q.db.QueryRow(ctx, findQuestionByID, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.ImageUrl,
		&i.Type,
		&i.Mark,
		&i.CreatedAt,
		&i.ScriptID,
	)
	return i, err
}

const findQuestionMark = `-- name: FindQuestionMark :one
SELECT get_question_mark($1::uuid)::integer
`

func (q *Queries) FindQuestionMark(ctx context.Context, questionID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, findQuestionMark, questionID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const findQuestionsForScript = `-- name: FindQuestionsForScript :many

SELECT questions.id, questions.text, questions.image_url, questions.type, questions.mark, questions.created_at, questions.script_id FROM
    scripts INNER JOIN questions on scripts.id = questions.script_id
WHERE scripts.id = $1
ORDER BY questions.created_at ASC
`

// Gets all the questions for a script ordered
// by time of creation
func (q *Queries) FindQuestionsForScript(ctx context.Context, id uuid.UUID) ([]Question, error) {
	rows, err := q.db.Query(ctx, findQuestionsForScript, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.ImageUrl,
			&i.Type,
			&i.Mark,
			&i.CreatedAt,
			&i.ScriptID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTextQuestionByID = `-- name: FindTextQuestionByID :one

SELECT id, is_short_text, type FROM text_questions WHERE text_questions.id = $1
`

func (q *Queries) FindTextQuestionByID(ctx context.Context, id uuid.UUID) (TextQuestion, error) {
	row := q.db.QueryRow(ctx, findTextQuestionByID, id)
	var i TextQuestion
	err := row.Scan(&i.ID, &i.IsShortText, &i.Type)
	return i, err
}

const replaceAnswerKeyForQuestion = `-- name: ReplaceAnswerKeyForQuestion :exec

WITH deleted AS (
    DELETE FROM answer_keys
    WHERE answer_keys.question_id = $1
    RETURNING 1
)
INSERT INTO answer_keys (
    question_id,
    value
) SELECT $1, unnest($2::text[]) FROM
    questions INNER JOIN scripts ON questions.script_id = scripts.id
    CROSS JOIN (SELECT count(*) FROM deleted) as _dep
WHERE questions.id = $1
    AND scripts.id = questions.script_id
    AND scripts.locked = false
`

type ReplaceAnswerKeyForQuestionParams struct {
	QuestionID uuid.UUID `json:"-"`
	AnswerKey  []string  `json:"answer_key"`
}

// Fully replace all answer key values for the
// question with the given ID
func (q *Queries) ReplaceAnswerKeyForQuestion(ctx context.Context, arg ReplaceAnswerKeyForQuestionParams) error {
	_, err := q.db.Exec(ctx, replaceAnswerKeyForQuestion, arg.QuestionID, arg.AnswerKey)
	return err
}

const replaceOptionsForQuestion = `-- name: ReplaceOptionsForQuestion :exec

WITH deleted AS (
    DELETE FROM options
    WHERE options.question_id = $1
)
INSERT INTO options (
    question_id,
    value,
    image_url
) SELECT $1, unnest($2::text[]), nullif(unnest($3::text[]), '') FROM
    questions INNER JOIN scripts
    ON questions.script_id = scripts.id
WHERE questions.id = $1
    AND scripts.id = questions.script_id
    AND scripts.locked = false
`

type ReplaceOptionsForQuestionParams struct {
	QuestionID uuid.UUID `json:"-"`
	Values     []string  `json:"values"`
	ImageUrls  []string  `json:"image_urls"`
}

// Fully replace all options with arrays of new values.
// Arrays passed are "zipped" together using unnest.
// Will not work with other subquestion types thanks to the
// foreign key constraints.
func (q *Queries) ReplaceOptionsForQuestion(ctx context.Context, arg ReplaceOptionsForQuestionParams) error {
	_, err := q.db.Exec(ctx, replaceOptionsForQuestion, arg.QuestionID, arg.Values, arg.ImageUrls)
	return err
}

const updateQuestionFields = `-- name: UpdateQuestionFields :exec

UPDATE questions SET
    text        = $2,
    image_url   = $3,
    mark        = $4
FROM scripts
WHERE questions.id = $1
    AND scripts.id = questions.script_id
    AND scripts.locked = false
`

type UpdateQuestionFieldsParams struct {
	ID       uuid.UUID `json:"id"`
	Text     string    `json:"text"`
	ImageUrl *string   `json:"image_url" mapstructure:"image_url"`
	Mark     *int32    `json:"mark"`
}

// Updates the parent question fields if possible.
func (q *Queries) UpdateQuestionFields(ctx context.Context, arg UpdateQuestionFieldsParams) error {
	_, err := q.db.Exec(ctx, updateQuestionFields,
		arg.ID,
		arg.Text,
		arg.ImageUrl,
		arg.Mark,
	)
	return err
}

const upsertChoiceQuestion = `-- name: UpsertChoiceQuestion :exec

WITH
deleted AS (
    SELECT delete_all_subquestions($1)
),
updated_type AS (
    UPDATE questions SET
        type = 'choice'
    WHERE questions.id = $1
    RETURNING questions.id
)
INSERT INTO choice_questions (
    id,
    is_multiple_choice
) SELECT $1, $2 FROM
    updated_type
    INNER JOIN questions ON questions.id = updated_type.id
    INNER JOIN scripts ON questions.script_id = scripts.id
    CROSS JOIN deleted
WHERE questions.id = $1
    AND scripts.locked = false
ON CONFLICT (id) DO UPDATE SET
    is_multiple_choice = EXCLUDED.is_multiple_choice
`

type UpsertChoiceQuestionParams struct {
	ID               uuid.UUID `json:"-"`
	IsMultipleChoice bool      `json:"is_multiple_choice" mapstructure:"is_multiple_choice"`
}

// Insert text-question values unless there is conflict,
// in which case update the existing subquestion.
//
// Inserting a new subquestion in this case will automatically
// delete all other subquestions & change the type of the
// parent question to maintain FK constraints.
func (q *Queries) UpsertChoiceQuestion(ctx context.Context, arg UpsertChoiceQuestionParams) error {
	_, err := q.db.Exec(ctx, upsertChoiceQuestion, arg.ID, arg.IsMultipleChoice)
	return err
}

const upsertTextQuestion = `-- name: UpsertTextQuestion :exec

WITH
deleted AS (
    SELECT delete_all_subquestions($1)
),
updated_type AS (
    UPDATE questions SET
        type = 'text'
    WHERE questions.id = $1
    RETURNING questions.id
)
INSERT INTO text_questions (
    id,
    is_short_text
) SELECT $1, $2 FROM
    updated_type
    INNER JOIN questions ON questions.id = updated_type.id
    INNER JOIN scripts ON questions.script_id = scripts.id
    CROSS JOIN deleted
WHERE questions.id = $1
    AND scripts.locked = false
ON CONFLICT (id) DO UPDATE SET
    is_short_text = EXCLUDED.is_short_text
`

type UpsertTextQuestionParams struct {
	ID          uuid.UUID `json:"-"`
	IsShortText bool      `json:"is_short_text" mapstructure:"is_short_text"`
}

// Insert text-question values unless there is conflict,
// in which case update the existing subquestion.
//
// Inserting a new subquestion in this case will automatically
// delete all other subquestions & change the type of the
// parent question to maintain FK constraints.
func (q *Queries) UpsertTextQuestion(ctx context.Context, arg UpsertTextQuestionParams) error {
	_, err := q.db.Exec(ctx, upsertTextQuestion, arg.ID, arg.IsShortText)
	return err
}
