// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: responses.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const autoMarkQuestionResponse = `-- name: AutoMarkQuestionResponse :one

WITH key_count AS (
    SELECT count(*) as value FROM answer_keys
    WHERE answer_keys.question_id = $2::uuid
)
UPDATE question_responses qr SET
    mark = CASE
        WHEN $1::boolean = true THEN get_question_mark($2::uuid)
        ELSE 0
    END
FROM responses r, key_count kc
WHERE
        r.id = qr.response_id
        AND r.session_id = $3::uuid
        AND r.examinee_id = $4::uuid
    AND qr.question_id = $2::uuid

    -- [X] Mark must be NULL prior
    -- [X] Submission must have a SUBMITTED status
    -- [X] Answer Key count is greater than 0

    AND qr.mark IS NULL
    AND r.status = 'submitted'
    AND kc.value > 0

RETURNING qr.response_id, qr.question_id, qr.mark, qr.feedback, qr.created_at
`

type AutoMarkQuestionResponseParams struct {
	IsCorrect  bool      `json:"is_correct"`
	QuestionID uuid.UUID `json:"question_id"`
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

// Automatically gives a mark to the question response. Will
// only give the mark as 0, or the maximum mark based
// on the application layer's is_correct value.
//
// If this fails for any of the question responses, then the whole
// thing should fail, meaning that post marking of these
// questions, all questions that can be automatically marked have been
// marked.
func (q *Queries) AutoMarkQuestionResponse(ctx context.Context, arg AutoMarkQuestionResponseParams) (QuestionResponse, error) {
	row := q.db.QueryRow(ctx, autoMarkQuestionResponse,
		arg.IsCorrect,
		arg.QuestionID,
		arg.SessionID,
		arg.ExamineeID,
	)
	var i QuestionResponse
	err := row.Scan(
		&i.ResponseID,
		&i.QuestionID,
		&i.Mark,
		&i.Feedback,
		&i.CreatedAt,
	)
	return i, err
}

const createResponse = `-- name: CreateResponse :one

INSERT INTO responses (
    session_id, examinee_id
) VALUES ($1, $2) RETURNING id, status, submitted_at, joined_at, examinee_id, session_id
`

type CreateResponseParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

// Creates a response given a session ID
// and an examinee ID. Will default to ENROLLED
// and enrolled_at set to the current time of execution
func (q *Queries) CreateResponse(ctx context.Context, arg CreateResponseParams) (Response, error) {
	row := q.db.QueryRow(ctx, createResponse, arg.SessionID, arg.ExamineeID)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const examineeFindResponses = `-- name: ExamineeFindResponses :many

SELECT id, status, submitted_at, joined_at, examinee_id, session_id FROM responses r
WHERE
    r.examinee_id = $1
AND r.status IN ('submitted', 'unreviewed', 'marked')
ORDER BY r.joined_at DESC
`

// Finds responses for an examinee using the examinee's ID
func (q *Queries) ExamineeFindResponses(ctx context.Context, examineeID uuid.UUID) ([]Response, error) {
	rows, err := q.db.Query(ctx, examineeFindResponses, examineeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Response{}
	for rows.Next() {
		var i Response
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.SubmittedAt,
			&i.JoinedAt,
			&i.ExamineeID,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const examinerMarkQuestionResponse = `-- name: ExaminerMarkQuestionResponse :exec

WITH key_count AS (
    SELECT count(*) as value FROM answer_keys
    WHERE answer_keys.question_id = $2::uuid
)
UPDATE question_responses qr SET
    mark        = greatest(0, least($1::integer, get_question_mark($2::uuid))),
    feedback    = $3::text
FROM responses r, key_count kc
WHERE
        r.id = qr.response_id
        AND r.session_id = $4::uuid
        AND r.examinee_id = $5::uuid
    AND qr.question_id = $2::uuid

    -- [X] Mark must be NULL prior
    -- [X] Submission must have an UNREVIEWED status
    -- [X] Answer Key count is equal to 0

    AND qr.mark IS NULL
    AND r.status = 'unreviewed'
    AND kc.value = 0

RETURNING qr.response_id, qr.question_id, qr.mark, qr.feedback, qr.created_at
`

type ExaminerMarkQuestionResponseParams struct {
	Mark       int32     `json:"mark"`
	QuestionID uuid.UUID `json:"question_id"`
	Feedback   string    `json:"feedback"`
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

// Sets the mark manually for an individual question response.
// Should clamp the mark to (0, get_question_mark(question_id))
func (q *Queries) ExaminerMarkQuestionResponse(ctx context.Context, arg ExaminerMarkQuestionResponseParams) error {
	_, err := q.db.Exec(ctx, examinerMarkQuestionResponse,
		arg.Mark,
		arg.QuestionID,
		arg.Feedback,
		arg.SessionID,
		arg.ExamineeID,
	)
	return err
}

const findQuestionResponses = `-- name: FindQuestionResponses :many

SELECT
    qr.response_id, qr.question_id, qr.mark, qr.feedback, qr.created_at,
    coalesce(
        array_agg(response_values.value) FILTER (WHERE response_values.value IS NOT NULL), '{}'
    )::text[] as value
FROM
    responses r
        JOIN question_responses qr ON qr.response_id = r.id
        LEFT JOIN response_values
            ON qr.question_id = response_values.question_id
            AND qr.response_id = response_values.response_id
WHERE
    r.session_id = $1::uuid
AND r.examinee_id = $2::uuid

GROUP BY qr.response_id, qr.question_id, qr.created_at
ORDER BY qr.created_at ASC
`

type FindQuestionResponsesParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

type FindQuestionResponsesRow struct {
	QuestionResponse QuestionResponse `json:"question_response"`
	Value            []string         `json:"value"`
}

// Gets all the question responses for a response, along
// with the response values (i.e. the response's answers) for that question.
func (q *Queries) FindQuestionResponses(ctx context.Context, arg FindQuestionResponsesParams) ([]FindQuestionResponsesRow, error) {
	rows, err := q.db.Query(ctx, findQuestionResponses, arg.SessionID, arg.ExamineeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindQuestionResponsesRow{}
	for rows.Next() {
		var i FindQuestionResponsesRow
		if err := rows.Scan(
			&i.QuestionResponse.ResponseID,
			&i.QuestionResponse.QuestionID,
			&i.QuestionResponse.Mark,
			&i.QuestionResponse.Feedback,
			&i.QuestionResponse.CreatedAt,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findResponseMarks = `-- name: FindResponseMarks :one

SELECT
    sum(qr.mark) as total,
    sum(get_question_mark(qr.question_id)) as maximum
FROM
    question_responses qr JOIN responses r ON qr.response_id = r.id
WHERE
    r.session_id = $1
AND r.examinee_id = $2
AND r.status = 'marked'
LIMIT 1
`

type FindResponseMarksParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

type FindResponseMarksRow struct {
	Total   int64 `json:"total"`
	Maximum int64 `json:"maximum"`
}

// Finds the marks for a response (must have MARKED status)
// given session ID and examinee ID. Will return the mark's total
// and maximum which represents: (total / maximum)
func (q *Queries) FindResponseMarks(ctx context.Context, arg FindResponseMarksParams) (FindResponseMarksRow, error) {
	row := q.db.QueryRow(ctx, findResponseMarks, arg.SessionID, arg.ExamineeID)
	var i FindResponseMarksRow
	err := row.Scan(&i.Total, &i.Maximum)
	return i, err
}

const findSessionResponses = `-- name: FindSessionResponses :many

SELECT
    responses.id, responses.status, responses.submitted_at, responses.joined_at, responses.examinee_id, responses.session_id
FROM
    responses JOIN users ON responses.examinee_id = users.id
WHERE responses.session_id = $1
`

type FindSessionResponsesRow struct {
	Response Response `json:"response"`
}

// Finds the responses for a session given the
// session ID. No extra information is added
func (q *Queries) FindSessionResponses(ctx context.Context, sessionID uuid.UUID) ([]FindSessionResponsesRow, error) {
	rows, err := q.db.Query(ctx, findSessionResponses, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSessionResponsesRow{}
	for rows.Next() {
		var i FindSessionResponsesRow
		if err := rows.Scan(
			&i.Response.ID,
			&i.Response.Status,
			&i.Response.SubmittedAt,
			&i.Response.JoinedAt,
			&i.Response.ExamineeID,
			&i.Response.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSessionResponsesWithUser = `-- name: FindSessionResponsesWithUser :many

SELECT
    responses.id, responses.status, responses.submitted_at, responses.joined_at, responses.examinee_id, responses.session_id,
    users.id, users.email, users.first_name, users.last_name, users.password_hash, users.role
FROM
    responses JOIN users ON responses.examinee_id = users.id
WHERE responses.session_id = $1
`

type FindSessionResponsesWithUserRow struct {
	Response Response `json:"response"`
	User     User     `json:"user"`
}

// Finds the responses for a session given the
// session ID, including each response's examinee information
func (q *Queries) FindSessionResponsesWithUser(ctx context.Context, sessionID uuid.UUID) ([]FindSessionResponsesWithUserRow, error) {
	rows, err := q.db.Query(ctx, findSessionResponsesWithUser, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSessionResponsesWithUserRow{}
	for rows.Next() {
		var i FindSessionResponsesWithUserRow
		if err := rows.Scan(
			&i.Response.ID,
			&i.Response.Status,
			&i.Response.SubmittedAt,
			&i.Response.JoinedAt,
			&i.Response.ExamineeID,
			&i.Response.SessionID,
			&i.User.ID,
			&i.User.Email,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.PasswordHash,
			&i.User.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSingleResponse = `-- name: FindSingleResponse :one

SELECT id, status, submitted_at, joined_at, examinee_id, session_id FROM responses r
WHERE
    r.session_id = $1
AND r.examinee_id = $2
LIMIT 1
`

type FindSingleResponseParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

// Find the response with matching session ID and examinee ID.
func (q *Queries) FindSingleResponse(ctx context.Context, arg FindSingleResponseParams) (Response, error) {
	row := q.db.QueryRow(ctx, findSingleResponse, arg.SessionID, arg.ExamineeID)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const replaceQuestionResponseValues = `-- name: ReplaceQuestionResponseValues :exec

WITH deleted AS (
    DELETE FROM response_values USING responses
    WHERE
        responses.id = response_values.response_id
    AND response.session_id = $3::uuid
    AND response.examinee_id = $4::uuid
    AND response_values.question_id = $1::uuid
    RETURNING 1
)
INSERT INTO response_values (
    response_id,
    question_id,
    value
) SELECT
    responses.id,
    $1::uuid,
    unnest($2::text[])
FROM
    responses
        JOIN sessions ON responses.session_id = sessions.id
        CROSS JOIN (SELECT count(*) FROM deleted) AS dep -- Ensures CTE deletion goes through
WHERE
    responses.session_id = $3::uuid
AND responses.examinee_id = $4::uuid
AND responses.status = 'editable'
AND sessions.status = 'started'
`

type ReplaceQuestionResponseValuesParams struct {
	QuestionID uuid.UUID `json:"question_id"`
	Value      []string  `json:"value"`
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

// Replaces the values (i.e. the answers) for
// a question response.
func (q *Queries) ReplaceQuestionResponseValues(ctx context.Context, arg ReplaceQuestionResponseValuesParams) error {
	_, err := q.db.Exec(ctx, replaceQuestionResponseValues,
		arg.QuestionID,
		arg.Value,
		arg.SessionID,
		arg.ExamineeID,
	)
	return err
}

const setQuestionResponsesForSession = `-- name: SetQuestionResponsesForSession :exec

WITH selected AS (
    SELECT
        responses.id as response_id,
        questions.id as question_id
    FROM
        scripts
            JOIN questions ON scripts.id = questions.script_id
            JOIN sessions ON sessions.script_id = scripts.id
            JOIN responses ON responses.session_id = sessions.id
    WHERE sessions.id = $1::uuid
    ORDER BY random()
)
INSERT INTO question_responses (
    response_id,
    question_id
) SELECT
    selected.response_id,
    selected.question_id
FROM selected
`

// Sets the questions for the submission of a user. Intended to
// be used after an examiner starts the exam session before
// responses are set as EDITABLE for examinees to answer
func (q *Queries) SetQuestionResponsesForSession(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setQuestionResponsesForSession, sessionID)
	return err
}
