// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: responses_status.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const debugGetCount = `-- name: DebugGetCount :one

SELECT count(*) AS value FROM
    responses r JOIN question_responses qr ON r.id = qr.response_id
WHERE
        r.session_id = $1::uuid
    AND r.examinee_id = $2::uuid
    AND qr.mark IS NULL
`

type DebugGetCountParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

func (q *Queries) DebugGetCount(ctx context.Context, arg DebugGetCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, debugGetCount, arg.SessionID, arg.ExamineeID)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const debugGetQuestionResponses = `-- name: DebugGetQuestionResponses :many
SELECT qr.mark, qr.feedback FROM
    responses r JOIN question_responses qr ON qr.response_id = r.id
WHERE
        r.session_id = $1::uuid
    AND r.examinee_id = $2::uuid
`

type DebugGetQuestionResponsesParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

type DebugGetQuestionResponsesRow struct {
	Mark     *int32 `json:"mark,omitempty"`
	Feedback string `json:"feedback,omitzero"`
}

func (q *Queries) DebugGetQuestionResponses(ctx context.Context, arg DebugGetQuestionResponsesParams) ([]DebugGetQuestionResponsesRow, error) {
	rows, err := q.db.Query(ctx, debugGetQuestionResponses, arg.SessionID, arg.ExamineeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DebugGetQuestionResponsesRow{}
	for rows.Next() {
		var i DebugGetQuestionResponsesRow
		if err := rows.Scan(&i.Mark, &i.Feedback); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const debugGetStatus = `-- name: DebugGetStatus :one

SELECT r.status FROM
    responses r JOIN question_responses qr ON r.id = qr.response_id
WHERE
        r.session_id = $1::uuid
    AND r.examinee_id = $2::uuid
`

type DebugGetStatusParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

func (q *Queries) DebugGetStatus(ctx context.Context, arg DebugGetStatusParams) (ResponseStatus, error) {
	row := q.db.QueryRow(ctx, debugGetStatus, arg.SessionID, arg.ExamineeID)
	var status ResponseStatus
	err := row.Scan(&status)
	return status, err
}

const findConnectableResponse = `-- name: FindConnectableResponse :one

SELECT responses.id FROM
    responses INNER JOIN sessions on responses.session_id = sessions.id
    WHERE responses.session_id = $1
    AND responses.examinee_id = $2
    AND (
        (sessions.status = 'open' AND responses.status IN ('enrolled', 'left'))
        OR (sessions.status = 'started' AND responses.status = 'disconnected')
    )
`

type FindConnectableResponseParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

// Returns the response ID if the examinee may open a websocket connection.
//
// OPEN:     enrolled or left (waiting room entry / reconnect)
// STARTED:  disconnected only (grace reconnect; flagged requires appeal first)
func (q *Queries) FindConnectableResponse(ctx context.Context, arg FindConnectableResponseParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findConnectableResponse, arg.SessionID, arg.ExamineeID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findResponseStatus = `-- name: FindResponseStatus :one

SELECT responses.status FROM responses
WHERE responses.session_id = $1
AND responses.examinee_id = $2
`

type FindResponseStatusParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

func (q *Queries) FindResponseStatus(ctx context.Context, arg FindResponseStatusParams) (ResponseStatus, error) {
	row := q.db.QueryRow(ctx, findResponseStatus, arg.SessionID, arg.ExamineeID)
	var status ResponseStatus
	err := row.Scan(&status)
	return status, err
}

const setResponseDisconnected = `-- name: SetResponseDisconnected :one

UPDATE responses SET
    status = 'disconnected'
WHERE responses.examinee_id = $1
AND responses.session_id = $2
AND responses.status IN ('editable')
RETURNING id, status, submitted_at, joined_at, examinee_id, session_id
`

type SetResponseDisconnectedParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Disconnect during STARTED while still eligible to answer (EDITABLE -> DISCONNECTED).
func (q *Queries) SetResponseDisconnected(ctx context.Context, arg SetResponseDisconnectedParams) (Response, error) {
	row := q.db.QueryRow(ctx, setResponseDisconnected, arg.ExamineeID, arg.SessionID)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setResponseDisconnectedFromFlagged = `-- name: SetResponseDisconnectedFromFlagged :one

UPDATE responses SET
    status = 'disconnected'
WHERE responses.examinee_id = $1
AND responses.session_id = $2
AND responses.status = 'flagged'
RETURNING id, status, submitted_at, joined_at, examinee_id, session_id
`

type SetResponseDisconnectedFromFlaggedParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Examiner grants appeal and client is disconnected in
// session hub (FLAGGED -> DISCONNECTED).
func (q *Queries) SetResponseDisconnectedFromFlagged(ctx context.Context, arg SetResponseDisconnectedFromFlaggedParams) (Response, error) {
	row := q.db.QueryRow(ctx, setResponseDisconnectedFromFlagged, arg.ExamineeID, arg.SessionID)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setResponseDisconnectedFromLeft = `-- name: SetResponseDisconnectedFromLeft :one

UPDATE responses SET
    status = 'disconnected'
WHERE responses.examinee_id = $1
AND responses.session_id = $2
AND responses.status = 'left'
RETURNING id, status, submitted_at, joined_at, examinee_id, session_id
`

type SetResponseDisconnectedFromLeftParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Examiner readmit after missing the start window (LEFT -> DISCONNECTED).
// Examinee reconnects with SetResponseEditableFromDisconnect.
func (q *Queries) SetResponseDisconnectedFromLeft(ctx context.Context, arg SetResponseDisconnectedFromLeftParams) (Response, error) {
	row := q.db.QueryRow(ctx, setResponseDisconnectedFromLeft, arg.ExamineeID, arg.SessionID)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setResponseEditableFromDisconnect = `-- name: SetResponseEditableFromDisconnect :one

UPDATE responses SET
    status = 'editable'
WHERE responses.examinee_id = $1
AND responses.session_id = $2
AND responses.status = 'disconnected'
RETURNING id, status, submitted_at, joined_at, examinee_id, session_id
`

type SetResponseEditableFromDisconnectParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Reconnect during STARTED after grace disconnect (DISCONNECTED -> EDITABLE).
func (q *Queries) SetResponseEditableFromDisconnect(ctx context.Context, arg SetResponseEditableFromDisconnectParams) (Response, error) {
	row := q.db.QueryRow(ctx, setResponseEditableFromDisconnect, arg.ExamineeID, arg.SessionID)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setResponseEditableFromFlagged = `-- name: SetResponseEditableFromFlagged :one

UPDATE responses SET
    status = 'editable'
WHERE responses.examinee_id = $1
AND responses.session_id = $2
AND responses.status = 'flagged'
RETURNING id, status, submitted_at, joined_at, examinee_id, session_id
`

type SetResponseEditableFromFlaggedParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Examiner grants appeal and client is connected in session
// hub (FLAGGED -> EDITABLE).
func (q *Queries) SetResponseEditableFromFlagged(ctx context.Context, arg SetResponseEditableFromFlaggedParams) (Response, error) {
	row := q.db.QueryRow(ctx, setResponseEditableFromFlagged, arg.ExamineeID, arg.SessionID)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setResponseFlaggedFromDisconnect = `-- name: SetResponseFlaggedFromDisconnect :one

UPDATE responses SET
    status = 'flagged'
WHERE responses.examinee_id = $1
AND responses.session_id = $2
AND responses.status = 'disconnected'
RETURNING id, status, submitted_at, joined_at, examinee_id, session_id
`

type SetResponseFlaggedFromDisconnectParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Flag response when grace period has expired
// (DISCONNECTED -> FLAGGED).
func (q *Queries) SetResponseFlaggedFromDisconnect(ctx context.Context, arg SetResponseFlaggedFromDisconnectParams) (Response, error) {
	row := q.db.QueryRow(ctx, setResponseFlaggedFromDisconnect, arg.ExamineeID, arg.SessionID)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setResponseFlaggedFromEditable = `-- name: SetResponseFlaggedFromEditable :one

UPDATE responses SET
    status = 'flagged'
WHERE responses.examinee_id = $1
AND responses.session_id = $2
AND responses.status = 'editable'
RETURNING id, status, submitted_at, joined_at, examinee_id, session_id
`

type SetResponseFlaggedFromEditableParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Flag response when if server flags user as cheating
// (EDITABLE -> FLAGGED).
func (q *Queries) SetResponseFlaggedFromEditable(ctx context.Context, arg SetResponseFlaggedFromEditableParams) (Response, error) {
	row := q.db.QueryRow(ctx, setResponseFlaggedFromEditable, arg.ExamineeID, arg.SessionID)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setResponseJoined = `-- name: SetResponseJoined :one

UPDATE responses SET
    status = 'joined'
WHERE responses.examinee_id = $1
AND responses.session_id = $2
AND responses.status IN ('enrolled', 'left')
RETURNING id, status, submitted_at, joined_at, examinee_id, session_id
`

type SetResponseJoinedParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Connect during OPEN: first entry (ENROLLED -> JOINED)
// or reconnect (LEFT -> JOINED).
func (q *Queries) SetResponseJoined(ctx context.Context, arg SetResponseJoinedParams) (Response, error) {
	row := q.db.QueryRow(ctx, setResponseJoined, arg.ExamineeID, arg.SessionID)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setResponseLeftFromJoined = `-- name: SetResponseLeftFromJoined :one

UPDATE responses SET
    status = 'left'
WHERE responses.examinee_id = $1
AND responses.session_id = $2
AND responses.status = 'joined'
RETURNING id, status, submitted_at, joined_at, examinee_id, session_id
`

type SetResponseLeftFromJoinedParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Disconnect during OPEN (JOINED -> LEFT). Ensures session start does not
// promote disconnected examinees to EDITABLE.
func (q *Queries) SetResponseLeftFromJoined(ctx context.Context, arg SetResponseLeftFromJoinedParams) (Response, error) {
	row := q.db.QueryRow(ctx, setResponseLeftFromJoined, arg.ExamineeID, arg.SessionID)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setResponseStatusOnConnect = `-- name: SetResponseStatusOnConnect :one

UPDATE responses SET
    status = CASE
        WHEN sessions.status = 'open' THEN 'joined'::response_status
        WHEN sessions.status = 'started' THEN 'editable'::response_status
    END
FROM sessions
WHERE responses.session_id = sessions.id
    AND responses.session_id = $1
    AND responses.examinee_id = $2
    AND (
        (sessions.status = 'open' AND responses.status IN ('enrolled', 'left'))
        OR (sessions.status = 'started' AND responses.status = 'disconnected')
    )
RETURNING responses.id, responses.status, responses.submitted_at, responses.joined_at, responses.examinee_id, responses.session_id
`

type SetResponseStatusOnConnectParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

// Set the response status to a connected state based on current
// response and session state
//
// response: (ENROLLED, LEFT) session: OPEN       -> JOINED
// response: (DISCONNECTED)   sesssion: STARTED   -> EDITABLE
func (q *Queries) SetResponseStatusOnConnect(ctx context.Context, arg SetResponseStatusOnConnectParams) (Response, error) {
	row := q.db.QueryRow(ctx, setResponseStatusOnConnect, arg.SessionID, arg.ExamineeID)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setResponseStatusOnDisconnect = `-- name: SetResponseStatusOnDisconnect :one

UPDATE responses SET
    status = CASE
        WHEN sessions.status = 'open' THEN 'left'::response_status
        WHEN sessions.status = 'started' THEN 'disconnected'::response_status
    END
FROM sessions
WHERE responses.session_id = sessions.id
    AND responses.session_id = $1
    AND responses.examinee_id = $2
    AND (
        (sessions.status = 'open' AND responses.status = 'joined')
        OR (sessions.status = 'started' AND responses.status = 'editable')
    )
RETURNING responses.id, responses.status, responses.submitted_at, responses.joined_at, responses.examinee_id, responses.session_id
`

type SetResponseStatusOnDisconnectParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

// Set the response status to a disconnected state based
// on current response and session state
//
// response: (JOINED)     session: OPEN       -> LEFT
// response: (EDITABLE)   sesssion: STARTED   -> DISCONNECTED
func (q *Queries) SetResponseStatusOnDisconnect(ctx context.Context, arg SetResponseStatusOnDisconnectParams) (Response, error) {
	row := q.db.QueryRow(ctx, setResponseStatusOnDisconnect, arg.SessionID, arg.ExamineeID)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setResponseStatusPostAutoMark = `-- name: SetResponseStatusPostAutoMark :one

UPDATE responses r SET

    status = CASE
        -- If there is a question yet to have a mark, set it as unreviewed
        WHEN EXISTS (
            SELECT 1 FROM question_responses qr
            WHERE qr.response_id = r.id
                AND qr.mark IS NULL
        ) THEN 'unreviewed'::response_status
        -- If there is no question yet to have a mark, set as fully marked
        ELSE 'marked'::response_status
    END

WHERE
        r.session_id = $1::uuid
    AND r.examinee_id = $2::uuid
    AND r.status = 'submitted'
RETURNING id, status, submitted_at, joined_at, examinee_id, session_id
`

type SetResponseStatusPostAutoMarkParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

// Set the status of the response post automatic marking.
// If the response still has questions yet to be marked, THEN
// set it as UNREVIEWED.
//
// Should only be used after marking every individual question
// that could be marked using AutoMarkQuestion().
//
// (SUBMITTED -> UNREVIEWED)    : len(questions.mark == NULL) >= 1
// (SUBMITTED -> MARKED)        : len(questions.mark == NULL) == 0
//
// The examiner should handle manually marking questions for responses
// post automatic marking that still have unresolved questions.
func (q *Queries) SetResponseStatusPostAutoMark(ctx context.Context, arg SetResponseStatusPostAutoMarkParams) (Response, error) {
	row := q.db.QueryRow(ctx, setResponseStatusPostAutoMark, arg.SessionID, arg.ExamineeID)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setResponseStatusPostManualMark = `-- name: SetResponseStatusPostManualMark :one

WITH unmarked_count AS  (
    SELECT count(*) AS value FROM
        responses r JOIN question_responses qr ON r.id = qr.response_id
    WHERE
            r.session_id = $1::uuid
        AND r.examinee_id = $2::uuid
        AND qr.mark IS NULL
)
UPDATE responses r SET
    status = 'marked'
FROM unmarked_count uc
WHERE
        r.session_id = $1::uuid
    AND r.examinee_id = $2::uuid
    AND r.status = 'unreviewed'
    AND uc.value = 0
RETURNING value, id, status, submitted_at, joined_at, examinee_id, session_id
`

type SetResponseStatusPostManualMarkParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

type SetResponseStatusPostManualMarkRow struct {
	Value       int64          `json:"value"`
	ID          uuid.UUID      `json:"id"`
	Status      ResponseStatus `json:"status"`
	SubmittedAt *time.Time     `json:"submitted_at"`
	JoinedAt    time.Time      `json:"joined_at"`
	ExamineeID  uuid.UUID      `json:"examinee_id"`
	SessionID   uuid.UUID      `json:"session_id"`
}

// Will set the status only to marked if the count of
// unmarked questions is 0. Should give error in application
// layer if otherwise.
//
// (UNREVIEWED -> MARKED)
func (q *Queries) SetResponseStatusPostManualMark(ctx context.Context, arg SetResponseStatusPostManualMarkParams) (SetResponseStatusPostManualMarkRow, error) {
	row := q.db.QueryRow(ctx, setResponseStatusPostManualMark, arg.SessionID, arg.ExamineeID)
	var i SetResponseStatusPostManualMarkRow
	err := row.Scan(
		&i.Value,
		&i.ID,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setResponseStatusesForStartedSession = `-- name: SetResponseStatusesForStartedSession :execrows

WITH enrolled_to_left AS (
    UPDATE responses SET
        status = 'left'
    WHERE responses.session_id = $1
    AND responses.status = 'enrolled'
    RETURNING id
)
UPDATE responses SET
    status = 'editable'
WHERE responses.session_id = $1
AND responses.status = 'joined'
`

// On session start: promote waiting-room examinees and lock out no-shows.
// Use after the session is STARTED and response questions are assigned.
//
// ENROLLED -> LEFT: enrolled but never connected during OPEN (see SetResponseJoined).
// JOINED -> EDITABLE: was in the waiting room when the exam started.
//
// Rows already LEFT (disconnected during OPEN) are unchanged and require
// examiner readmit (SetResponseDisconnectedFromLeft) to participate.
func (q *Queries) SetResponseStatusesForStartedSession(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, setResponseStatusesForStartedSession, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setResponseSubmitted = `-- name: SetResponseSubmitted :one

UPDATE responses SET
    status          = 'submitted',
    submitted_at    = now()
WHERE responses.examinee_id = $1
AND responses.session_id = $2
AND responses.status = 'editable'
RETURNING id, status, submitted_at, joined_at, examinee_id, session_id
`

type SetResponseSubmittedParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Voluntary final submit by the examinee (EDITABLE -> SUBMITTED).
func (q *Queries) SetResponseSubmitted(ctx context.Context, arg SetResponseSubmittedParams) (Response, error) {
	row := q.db.QueryRow(ctx, setResponseSubmitted, arg.ExamineeID, arg.SessionID)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const submitAllResponsesForSession = `-- name: SubmitAllResponsesForSession :execrows

UPDATE responses SET
    status          = 'submitted',
    submitted_at    = now()
WHERE responses.session_id = $1
AND responses.status NOT IN ('submitted', 'marked', 'joined', 'enrolled')
`

// On session end: auto-submit all in-progress responses for the session.
// Updates LEFT, EDITABLE, DISCONNECTED, and FLAGGED to SUBMITTED.
//
// ENROLLED and JOINED are excluded (should not exist after session start;
// see SetResponseStatusesForStartedSession). SUBMITTED and MARKED are terminal.
func (q *Queries) SubmitAllResponsesForSession(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, submitAllResponsesForSession, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
