// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scripts.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createScript = `-- name: CreateScript :one

INSERT INTO scripts (
    title,
    heading,
    description,
    creator_id
) VALUES ($1, $2, $3, $4) RETURNING id, title, heading, description, locked, created_at, last_modified_at, creator_id
`

type CreateScriptParams struct {
	Title       string    `json:"title"`
	Heading     string    `json:"heading"`
	Description string    `json:"description"`
	CreatorID   uuid.UUID `json:"creator_id"`
}

// Creates a new script
func (q *Queries) CreateScript(ctx context.Context, arg CreateScriptParams) (Script, error) {
	row := q.db.QueryRow(ctx, createScript,
		arg.Title,
		arg.Heading,
		arg.Description,
		arg.CreatorID,
	)
	var i Script
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Heading,
		&i.Description,
		&i.Locked,
		&i.CreatedAt,
		&i.LastModifiedAt,
		&i.CreatorID,
	)
	return i, err
}

const deleteScript = `-- name: DeleteScript :exec

DELETE FROM scripts
WHERE scripts.id = $1
    AND scripts.locked = false
`

// Deletes the script if possible
func (q *Queries) DeleteScript(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScript, id)
	return err
}

const findScriptByID = `-- name: FindScriptByID :one

SELECT id, title, heading, description, locked, created_at, last_modified_at, creator_id FROM scripts
WHERE scripts.id = $1
`

// Finds a script by its ID
func (q *Queries) FindScriptByID(ctx context.Context, id uuid.UUID) (Script, error) {
	row := q.db.QueryRow(ctx, findScriptByID, id)
	var i Script
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Heading,
		&i.Description,
		&i.Locked,
		&i.CreatedAt,
		&i.LastModifiedAt,
		&i.CreatorID,
	)
	return i, err
}

const findScriptCountForExaminer = `-- name: FindScriptCountForExaminer :one

SELECT COUNT(*) FROM scripts
WHERE
    scripts.creator_id = $1::UUID
    AND ($2::TEXT = '' OR scripts.title ILIKE '%' || $2::TEXT || '%')
`

type FindScriptCountForExaminerParams struct {
	ExaminerID uuid.UUID `json:"examiner_id"`
	Search     string    `json:"search"`
}

// Finds the number of scripts belonging to the
// examiner with the search query
func (q *Queries) FindScriptCountForExaminer(ctx context.Context, arg FindScriptCountForExaminerParams) (int64, error) {
	row := q.db.QueryRow(ctx, findScriptCountForExaminer, arg.ExaminerID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findScriptForSubmission = `-- name: FindScriptForSubmission :one

SELECT scripts.id, scripts.title, scripts.heading, scripts.description, scripts.locked, scripts.created_at, scripts.last_modified_at, scripts.creator_id FROM
    scripts INNER JOIN sessions ON scripts.id = sessions.script_id
    INNER JOIN submissions ON submissions.session_id = sessions.id
WHERE submissions.id = $1::uuid LIMIT 1
`

func (q *Queries) FindScriptForSubmission(ctx context.Context, submissionID uuid.UUID) (Script, error) {
	row := q.db.QueryRow(ctx, findScriptForSubmission, submissionID)
	var i Script
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Heading,
		&i.Description,
		&i.Locked,
		&i.CreatedAt,
		&i.LastModifiedAt,
		&i.CreatorID,
	)
	return i, err
}

const findScriptsForExaminer = `-- name: FindScriptsForExaminer :many

SELECT id, title, heading, description, locked, created_at, last_modified_at, creator_id FROM scripts
WHERE scripts.creator_id = $1::UUID
    AND ($2::TEXT = '' OR scripts.title ILIKE '%' || $2::TEXT || '%')
    AND (scripts.last_modified_at, scripts.id) < ($3::TIMESTAMPTZ, $4::UUID)
ORDER BY scripts.last_modified_at DESC, scripts.id DESC
LIMIT $5
`

type FindScriptsForExaminerParams struct {
	ExaminerID uuid.UUID `json:"examiner_id"`
	Search     string    `json:"search"`
	CursorTs   time.Time `json:"cursor_ts"`
	CursorID   uuid.UUID `json:"cursor_id"`
	PageSize   int32     `json:"page_size"`
}

// Gets the scripts belonging to the examiner
// with cursor pagination and a search query
func (q *Queries) FindScriptsForExaminer(ctx context.Context, arg FindScriptsForExaminerParams) ([]Script, error) {
	rows, err := q.db.Query(ctx, findScriptsForExaminer,
		arg.ExaminerID,
		arg.Search,
		arg.CursorTs,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Script{}
	for rows.Next() {
		var i Script
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Heading,
			&i.Description,
			&i.Locked,
			&i.CreatedAt,
			&i.LastModifiedAt,
			&i.CreatorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScriptFields = `-- name: UpdateScriptFields :one

UPDATE scripts SET
    title       = $2,
    heading     = $3,
    description = $4
WHERE scripts.id = $1
    AND scripts.locked = false
RETURNING id
`

type UpdateScriptFieldsParams struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Heading     string    `json:"heading"`
	Description string    `json:"description"`
}

// Updates the script if possible
func (q *Queries) UpdateScriptFields(ctx context.Context, arg UpdateScriptFieldsParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateScriptFields,
		arg.ID,
		arg.Title,
		arg.Heading,
		arg.Description,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
