// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scripts.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createChoiceQuestion = `-- name: CreateChoiceQuestion :one


WITH inserted AS (
    INSERT INTO questions (
        script_id,
        type,
        text,
        image_url
    ) SELECT $4::uuid, 'choice', $1, $2 FROM scripts
    WHERE scripts.id = $4::uuid
        AND scripts.locked = false
    RETURNING id, text, image_url, type, created_at, script_id
) INSERT INTO choice_questions (
    id,
    is_multiple_choice
) SELECT inserted.id, $3 FROM
    inserted INNER JOIN scripts ON inserted.script_id = scripts.id
WHERE scripts.id = $4::uuid
AND scripts.locked = false
RETURNING id
`

type CreateChoiceQuestionParams struct {
	Text             string    `json:"text"`
	ImageUrl         *string   `json:"image_url" mapstructure:"image_url"`
	IsMultipleChoice bool      `json:"is_multiple_choice" mapstructure:"is_multiple_choice"`
	ScriptID         uuid.UUID `json:"script_id"`
}

// ---------------------------------------------------------------
// - Creating Questions ------------------------------------------
// ---------------------------------------------------------------
// Creates a new choice question
// ------------------------------
func (q *Queries) CreateChoiceQuestion(ctx context.Context, arg CreateChoiceQuestionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createChoiceQuestion,
		arg.Text,
		arg.ImageUrl,
		arg.IsMultipleChoice,
		arg.ScriptID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createScript = `-- name: CreateScript :one

INSERT INTO scripts (
    title,
    heading,
    description,
    creator_id
) VALUES ($1, $2, $3, $4) RETURNING id, title, heading, description, locked, created_at, last_modified_at, creator_id
`

type CreateScriptParams struct {
	Title       string    `json:"title"`
	Heading     string    `json:"heading"`
	Description string    `json:"description"`
	CreatorID   uuid.UUID `json:"creator_id"`
}

// Creates a new script
// ---------------------
func (q *Queries) CreateScript(ctx context.Context, arg CreateScriptParams) (Script, error) {
	row := q.db.QueryRow(ctx, createScript,
		arg.Title,
		arg.Heading,
		arg.Description,
		arg.CreatorID,
	)
	var i Script
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Heading,
		&i.Description,
		&i.Locked,
		&i.CreatedAt,
		&i.LastModifiedAt,
		&i.CreatorID,
	)
	return i, err
}

const createTextQuestion = `-- name: CreateTextQuestion :one

WITH inserted AS (
    INSERT INTO questions (
        script_id,
        type,
        text,
        image_url
    ) SELECT $4::uuid, 'text', $1, $2 FROM scripts
    WHERE scripts.id = $4::uuid
        AND scripts.locked = false
    RETURNING id, text, image_url, type, created_at, script_id
) INSERT INTO text_questions (
    id,
    is_short_text
) SELECT inserted.id, $3 FROM
    inserted INNER JOIN scripts ON inserted.script_id = scripts.id
WHERE scripts.id = $4::uuid
AND scripts.locked = false
RETURNING id
`

type CreateTextQuestionParams struct {
	Text        string    `json:"text"`
	ImageUrl    *string   `json:"image_url" mapstructure:"image_url"`
	IsShortText bool      `json:"is_short_text" mapstructure:"is_short_text"`
	ScriptID    uuid.UUID `json:"script_id"`
}

// Creates a new text question
// ----------------------------
func (q *Queries) CreateTextQuestion(ctx context.Context, arg CreateTextQuestionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTextQuestion,
		arg.Text,
		arg.ImageUrl,
		arg.IsShortText,
		arg.ScriptID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteQuestion = `-- name: DeleteQuestion :exec

DELETE FROM questions
USING scripts
WHERE questions.id = $1
    AND scripts.id = questions.script_id
    AND scripts.locked = false
`

// Deletes the question if possible.
// cascades to child components (e.g. subquestions & options)
// -----------------------------------------------------------
func (q *Queries) DeleteQuestion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuestion, id)
	return err
}

const deleteScript = `-- name: DeleteScript :exec

DELETE FROM scripts
WHERE scripts.id = $1
    AND scripts.locked = false
`

// Deletes the script if possible
// -------------------------------
func (q *Queries) DeleteScript(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScript, id)
	return err
}

const findAnswerKeyForQuestion = `-- name: FindAnswerKeyForQuestion :many

SELECT answer_keys.value FROM answer_keys
WHERE answer_keys.question_id = $1
`

// Finds the answer key for a question as a list
// ----------------------------------------------
func (q *Queries) FindAnswerKeyForQuestion(ctx context.Context, questionID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, findAnswerKeyForQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var value string
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findChoiceQuestionByID = `-- name: FindChoiceQuestionByID :one

SELECT id, is_multiple_choice, type FROM choice_questions
WHERE choice_questions.id = $1
`

// ---------------------------------------------------------------
// ---------------------------------------------------------------
func (q *Queries) FindChoiceQuestionByID(ctx context.Context, id uuid.UUID) (ChoiceQuestion, error) {
	row := q.db.QueryRow(ctx, findChoiceQuestionByID, id)
	var i ChoiceQuestion
	err := row.Scan(&i.ID, &i.IsMultipleChoice, &i.Type)
	return i, err
}

const findOptionsForQuestion = `-- name: FindOptionsForQuestion :many

SELECT value, question_id, image_url, created_at FROM options
    WHERE options.question_id = $1
    ORDER BY options.created_at ASC
`

// ---------------------------------------------------------------
// - Querying Options --------------------------------------------
// ---------------------------------------------------------------
// Finds options for a question order by creation.
// Used for obtaining options for a question for editing
// ------------------------------------------------------
func (q *Queries) FindOptionsForQuestion(ctx context.Context, questionID uuid.UUID) ([]Option, error) {
	rows, err := q.db.Query(ctx, findOptionsForQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Option{}
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.Value,
			&i.QuestionID,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOptionsForQuestionShuffled = `-- name: FindOptionsForQuestionShuffled :many
SELECT value, question_id, image_url, created_at FROM options
    WHERE options.question_id = $1
    ORDER BY random()
`

// Finds options for a question unordered. Used for
// obtaining options for a question during an exam session
// --------------------------------------------------------
func (q *Queries) FindOptionsForQuestionShuffled(ctx context.Context, questionID uuid.UUID) ([]Option, error) {
	rows, err := q.db.Query(ctx, findOptionsForQuestionShuffled, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Option{}
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.Value,
			&i.QuestionID,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findQuestionByID = `-- name: FindQuestionByID :one

SELECT id, text, image_url, type, created_at, script_id FROM questions
WHERE questions.id = $1
`

// Gets a single question
// -----------------------
func (q *Queries) FindQuestionByID(ctx context.Context, id uuid.UUID) (Question, error) {
	row := q.db.QueryRow(ctx, findQuestionByID, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.ImageUrl,
		&i.Type,
		&i.CreatedAt,
		&i.ScriptID,
	)
	return i, err
}

const findQuestionsForScript = `-- name: FindQuestionsForScript :many


SELECT questions.id, questions.text, questions.image_url, questions.type, questions.created_at, questions.script_id FROM
    scripts INNER JOIN questions on scripts.id = questions.script_id
WHERE scripts.id = $1
ORDER BY questions.created_at ASC
`

// ---------------------------------------------------------------
// - Querying Questions ------------------------------------------
// ---------------------------------------------------------------
// Gets all the questions for a script ordered
// by time of creation
// --------------------------------------------
func (q *Queries) FindQuestionsForScript(ctx context.Context, id uuid.UUID) ([]Question, error) {
	rows, err := q.db.Query(ctx, findQuestionsForScript, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.ImageUrl,
			&i.Type,
			&i.CreatedAt,
			&i.ScriptID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findQuestionsForScriptShuffled = `-- name: FindQuestionsForScriptShuffled :many

SELECT questions.id, questions.text, questions.image_url, questions.type, questions.created_at, questions.script_id FROM
    scripts INNER JOIN questions ON scripts.id = questions.script_id
WHERE scripts.id = $1
ORDER BY random()
`

// Gets all the questions for a script as shuffled
// ------------------------------------------------
func (q *Queries) FindQuestionsForScriptShuffled(ctx context.Context, id uuid.UUID) ([]Question, error) {
	rows, err := q.db.Query(ctx, findQuestionsForScriptShuffled, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.ImageUrl,
			&i.Type,
			&i.CreatedAt,
			&i.ScriptID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findScriptByID = `-- name: FindScriptByID :one


SELECT id, title, heading, description, locked, created_at, last_modified_at, creator_id FROM scripts
WHERE scripts.id = $1
`

// ---------------------------------------------------------------
// ---------------------------------------------------------------
// Finds a script by its ID
// -------------------------
func (q *Queries) FindScriptByID(ctx context.Context, id uuid.UUID) (Script, error) {
	row := q.db.QueryRow(ctx, findScriptByID, id)
	var i Script
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Heading,
		&i.Description,
		&i.Locked,
		&i.CreatedAt,
		&i.LastModifiedAt,
		&i.CreatorID,
	)
	return i, err
}

const findScriptCountForExaminer = `-- name: FindScriptCountForExaminer :one

SELECT COUNT(*) FROM scripts
WHERE scripts.creator_id = $1
`

// Finds the number of scripts belonging to the
// examiner
// --------------------------------------------
func (q *Queries) FindScriptCountForExaminer(ctx context.Context, creatorID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, findScriptCountForExaminer, creatorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findScriptsForExaminer = `-- name: FindScriptsForExaminer :many


SELECT id, title, heading, description, locked, created_at, last_modified_at, creator_id FROM scripts
WHERE scripts.creator_id = $1::UUID
    AND (scripts.last_modified_at, scripts.id) < ($2::TIMESTAMPTZ, $3::UUID)
ORDER BY scripts.last_modified_at DESC, scripts.id DESC
LIMIT $4
`

type FindScriptsForExaminerParams struct {
	ExaminerID uuid.UUID `json:"examiner_id"`
	CursorTs   time.Time `json:"cursor_ts"`
	CursorID   uuid.UUID `json:"cursor_id"`
	PageSize   int32     `json:"page_size"`
}

// ---------------------------------------------------------------
// - Finding Scripts ---------------------------------------------
// ---------------------------------------------------------------
// Gets the scripts belonging to the examiner
// with cursor pagination
// -------------------------------------------
func (q *Queries) FindScriptsForExaminer(ctx context.Context, arg FindScriptsForExaminerParams) ([]Script, error) {
	rows, err := q.db.Query(ctx, findScriptsForExaminer,
		arg.ExaminerID,
		arg.CursorTs,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Script{}
	for rows.Next() {
		var i Script
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Heading,
			&i.Description,
			&i.Locked,
			&i.CreatedAt,
			&i.LastModifiedAt,
			&i.CreatorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTextQuestionByID = `-- name: FindTextQuestionByID :one
SELECT id, is_short_text, type FROM text_questions WHERE text_questions.id = $1
`

func (q *Queries) FindTextQuestionByID(ctx context.Context, id uuid.UUID) (TextQuestion, error) {
	row := q.db.QueryRow(ctx, findTextQuestionByID, id)
	var i TextQuestion
	err := row.Scan(&i.ID, &i.IsShortText, &i.Type)
	return i, err
}

const replaceAnswerKeyForQuestion = `-- name: ReplaceAnswerKeyForQuestion :exec


WITH deleted AS (
    DELETE FROM answer_keys
    WHERE answer_keys.question_id = $1
) INSERT INTO answer_keys (
    question_id,
    value
) SELECT $1, unnest($2::text[]) FROM
    questions INNER JOIN scripts
    ON questions.script_id = scripts.id
WHERE questions.id = $1
    AND scripts.id = questions.script_id
    AND scripts.locked = false
`

type ReplaceAnswerKeyForQuestionParams struct {
	QuestionID uuid.UUID `json:"-"`
	AnswerKey  []string  `json:"answer_key"`
}

// ---------------------------------------------------------------
// - Answer Key --------------------------------------------------
// ---------------------------------------------------------------
// Fully replace all answer key values for the
// question with the given ID
// --------------------------------------------
func (q *Queries) ReplaceAnswerKeyForQuestion(ctx context.Context, arg ReplaceAnswerKeyForQuestionParams) error {
	_, err := q.db.Exec(ctx, replaceAnswerKeyForQuestion, arg.QuestionID, arg.AnswerKey)
	return err
}

const replaceOptionsForQuestion = `-- name: ReplaceOptionsForQuestion :exec


WITH deleted AS (
    DELETE FROM options
    WHERE options.question_id = $1
) INSERT INTO options (
    question_id,
    value,
    image_url
) SELECT $1, unnest($2::text[]), nullif(unnest($3::text[]), '') FROM
    questions INNER JOIN scripts
    ON questions.script_id = scripts.id
WHERE questions.id = $1
    AND scripts.id = questions.script_id
    AND scripts.locked = false
`

type ReplaceOptionsForQuestionParams struct {
	QuestionID uuid.UUID `json:"-"`
	Values     []string  `json:"values"`
	ImageUrls  []string  `json:"image_urls"`
}

// ---------------------------------------------------------------
// - Options -----------------------------------------------------
// ---------------------------------------------------------------
// Fully replace all options with arrays of new values.
// Arrays passed are "zipped" together using unnest.
// Will not work with other subquestion types thanks to the
// foreign key constraints.
// ---------------------------------------------------------
func (q *Queries) ReplaceOptionsForQuestion(ctx context.Context, arg ReplaceOptionsForQuestionParams) error {
	_, err := q.db.Exec(ctx, replaceOptionsForQuestion, arg.QuestionID, arg.Values, arg.ImageUrls)
	return err
}

const searchScriptCountForExaminer = `-- name: SearchScriptCountForExaminer :one

SELECT COUNT(*) FROM scripts
WHERE
    scripts.creator_id = $1::UUID
    AND scripts.title ILIKE '%' || $2::TEXT || '%'
`

type SearchScriptCountForExaminerParams struct {
	ExaminerID uuid.UUID `json:"examiner_id"`
	Search     string    `json:"search"`
}

// Finds the number of scripts belonging to the
// examiner with the search query
// --------------------------------------------
func (q *Queries) SearchScriptCountForExaminer(ctx context.Context, arg SearchScriptCountForExaminerParams) (int64, error) {
	row := q.db.QueryRow(ctx, searchScriptCountForExaminer, arg.ExaminerID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchScriptsForExaminer = `-- name: SearchScriptsForExaminer :many


SELECT id, title, heading, description, locked, created_at, last_modified_at, creator_id FROM scripts
WHERE scripts.creator_id = $1::UUID
    AND scripts.title ILIKE '%' || $2::TEXT || '%'
    AND (scripts.last_modified_at, scripts.id) < ($3::TIMESTAMPTZ, $4::UUID)
ORDER BY scripts.last_modified_at DESC, scripts.id DESC
LIMIT $5
`

type SearchScriptsForExaminerParams struct {
	ExaminerID uuid.UUID `json:"examiner_id"`
	Search     string    `json:"search"`
	CursorTs   time.Time `json:"cursor_ts"`
	CursorID   uuid.UUID `json:"cursor_id"`
	PageSize   int32     `json:"page_size"`
}

// ---------------------------------------------------------------
// ---------------------------------------------------------------
// Gets the scripts belonging to the examiner
// with cursor pagination and a search query
// -------------------------------------------
func (q *Queries) SearchScriptsForExaminer(ctx context.Context, arg SearchScriptsForExaminerParams) ([]Script, error) {
	rows, err := q.db.Query(ctx, searchScriptsForExaminer,
		arg.ExaminerID,
		arg.Search,
		arg.CursorTs,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Script{}
	for rows.Next() {
		var i Script
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Heading,
			&i.Description,
			&i.Locked,
			&i.CreatedAt,
			&i.LastModifiedAt,
			&i.CreatorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestionFields = `-- name: UpdateQuestionFields :exec


UPDATE questions SET
    text        = $2,
    image_url   = $3
FROM scripts
WHERE questions.id = $1
    AND scripts.id = questions.script_id
    AND scripts.locked = false
`

type UpdateQuestionFieldsParams struct {
	ID       uuid.UUID `json:"id"`
	Text     string    `json:"text"`
	ImageUrl *string   `json:"image_url" mapstructure:"image_url"`
}

// ---------------------------------------------------------------
// - Manipulating Questions --------------------------------------
// ---------------------------------------------------------------
// Updates the parent question fields if possible.
// ------------------------------------------------
func (q *Queries) UpdateQuestionFields(ctx context.Context, arg UpdateQuestionFieldsParams) error {
	_, err := q.db.Exec(ctx, updateQuestionFields, arg.ID, arg.Text, arg.ImageUrl)
	return err
}

const updateScriptFields = `-- name: UpdateScriptFields :one

UPDATE scripts SET
    title       = $2,
    heading     = $3,
    description = $4
WHERE scripts.id = $1
    AND scripts.locked = false
RETURNING id
`

type UpdateScriptFieldsParams struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Heading     string    `json:"heading"`
	Description string    `json:"description"`
}

// Updates the script if possible
// -------------------------------
func (q *Queries) UpdateScriptFields(ctx context.Context, arg UpdateScriptFieldsParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateScriptFields,
		arg.ID,
		arg.Title,
		arg.Heading,
		arg.Description,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertChoiceQuestion = `-- name: UpsertChoiceQuestion :exec

WITH deleted AS (
    SELECT delete_all_subquestions($1)
), updated_type AS (
    UPDATE questions SET
        type = 'choice'
    WHERE questions.id = $1
    RETURNING questions.id
) INSERT INTO choice_questions (
    id,
    is_multiple_choice
) SELECT $1, $2 FROM
    updated_type
    INNER JOIN questions ON questions.id = updated_type.id
    INNER JOIN scripts ON questions.script_id = scripts.id
    CROSS JOIN deleted
WHERE questions.id = $1
    AND scripts.locked = false
ON CONFLICT (id) DO UPDATE SET
    is_multiple_choice = EXCLUDED.is_multiple_choice
`

type UpsertChoiceQuestionParams struct {
	ID               uuid.UUID `json:"-"`
	IsMultipleChoice bool      `json:"is_multiple_choice" mapstructure:"is_multiple_choice"`
}

// Insert text-question values unless there is conflict,
// in which case update the existing subquestion.
//
// Inserting a new subquestion in this case will automatically
// delete all other subquestions & change the type of the
// parent question to maintain FK constraints.
// -------------------------------------------------------------
func (q *Queries) UpsertChoiceQuestion(ctx context.Context, arg UpsertChoiceQuestionParams) error {
	_, err := q.db.Exec(ctx, upsertChoiceQuestion, arg.ID, arg.IsMultipleChoice)
	return err
}

const upsertTextQuestion = `-- name: UpsertTextQuestion :exec


WITH deleted AS (
    SELECT delete_all_subquestions($1)
), updated_type AS (
    UPDATE questions SET
        type = 'text'
    WHERE questions.id = $1
    RETURNING questions.id
) INSERT INTO text_questions (
    id,
    is_short_text
) SELECT $1, $2 FROM
    updated_type
    INNER JOIN questions ON questions.id = updated_type.id
    INNER JOIN scripts ON questions.script_id = scripts.id
    CROSS JOIN deleted
WHERE questions.id = $1
    AND scripts.locked = false
ON CONFLICT (id) DO UPDATE SET
    is_short_text = EXCLUDED.is_short_text
`

type UpsertTextQuestionParams struct {
	ID          uuid.UUID `json:"-"`
	IsShortText bool      `json:"is_short_text" mapstructure:"is_short_text"`
}

// ---------------------------------------------------------------
// ---------------------------------------------------------------
// Insert text-question values unless there is conflict,
// in which case update the existing subquestion.
//
// Inserting a new subquestion in this case will automatically
// delete all other subquestions & change the type of the
// parent question to maintain FK constraints.
// -------------------------------------------------------------
func (q *Queries) UpsertTextQuestion(ctx context.Context, arg UpsertTextQuestionParams) error {
	_, err := q.db.Exec(ctx, upsertTextQuestion, arg.ID, arg.IsShortText)
	return err
}
