// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const closeSession = `-- name: CloseSession :one

UPDATE sessions SET
    status = 'closed'
WHERE sessions.id = $1
    AND sessions.status = 'open'
RETURNING id, title, status, question_count, started_at, ended_at, join_code, allow_any_examinee, created_at, creator_id, script_id
`

// Puts the session in CLOSED mode (default mode). While in
// CLOSED mode, examinees cannot join the session. Only
// sessions in OPEN mode can be closed.
func (q *Queries) CloseSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, closeSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.QuestionCount,
		&i.StartedAt,
		&i.EndedAt,
		&i.JoinCode,
		&i.AllowAnyExaminee,
		&i.CreatedAt,
		&i.CreatorID,
		&i.ScriptID,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    creator_id,
    script_id,
    title,
    join_code
) VALUES ($1, $2, $3, $4) RETURNING id
`

type CreateSessionParams struct {
	CreatorID uuid.UUID `json:"creator_id"`
	ScriptID  uuid.UUID `json:"script_id"`
	Title     string    `json:"title"`
	JoinCode  string    `json:"join_code"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.CreatorID,
		arg.ScriptID,
		arg.Title,
		arg.JoinCode,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteSessionByID = `-- name: DeleteSessionByID :exec

DELETE FROM sessions
WHERE sessions.status = 'closed'
    AND sessions.id = $1
`

// Deletes a session only if it is CLOSED
func (q *Queries) DeleteSessionByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionByID, id)
	return err
}

const endSession = `-- name: EndSession :one

UPDATE sessions SET
    status      = 'ended',
    ended_at    = now()
WHERE sessions.id = $1
    AND sessions.status = 'started'
RETURNING id, title, status, question_count, started_at, ended_at, join_code, allow_any_examinee, created_at, creator_id, script_id
`

// Sets the session to ENDED mode. Only sessions in STARTED
// mode can be started.
func (q *Queries) EndSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, endSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.QuestionCount,
		&i.StartedAt,
		&i.EndedAt,
		&i.JoinCode,
		&i.AllowAnyExaminee,
		&i.CreatedAt,
		&i.CreatorID,
		&i.ScriptID,
	)
	return i, err
}

const findSessionByID = `-- name: FindSessionByID :one
SELECT id, title, status, question_count, started_at, ended_at, join_code, allow_any_examinee, created_at, creator_id, script_id FROM sessions
WHERE sessions.id = $1 LIMIT 1
`

func (q *Queries) FindSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.QuestionCount,
		&i.StartedAt,
		&i.EndedAt,
		&i.JoinCode,
		&i.AllowAnyExaminee,
		&i.CreatedAt,
		&i.CreatorID,
		&i.ScriptID,
	)
	return i, err
}

const findSessionByJoinCode = `-- name: FindSessionByJoinCode :one
SELECT id, title, status, question_count, started_at, ended_at, join_code, allow_any_examinee, created_at, creator_id, script_id FROM sessions
WHERE sessions.join_code ILIKE $1
    AND sessions.status = 'open'
LIMIT 1
`

func (q *Queries) FindSessionByJoinCode(ctx context.Context, joinCode string) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionByJoinCode, joinCode)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.QuestionCount,
		&i.StartedAt,
		&i.EndedAt,
		&i.JoinCode,
		&i.AllowAnyExaminee,
		&i.CreatedAt,
		&i.CreatorID,
		&i.ScriptID,
	)
	return i, err
}

const findSessionCountForExaminer = `-- name: FindSessionCountForExaminer :one

SELECT COUNT(*) FROM sessions
WHERE
    sessions.creator_id = $1::UUID
    AND ($2::TEXT = '' OR sessions.title ILIKE '%' || $2::TEXT || '%')
    AND ($3::session_status IS NULL OR sessions.status = $3::session_status)
`

type FindSessionCountForExaminerParams struct {
	ExaminerID uuid.UUID         `json:"examiner_id"`
	Search     string            `json:"search"`
	Status     NullSessionStatus `json:"status"`
}

// Finds the number of sessions belonging to the
// examiner with the search query
func (q *Queries) FindSessionCountForExaminer(ctx context.Context, arg FindSessionCountForExaminerParams) (int64, error) {
	row := q.db.QueryRow(ctx, findSessionCountForExaminer, arg.ExaminerID, arg.Search, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findSessionsForExaminer = `-- name: FindSessionsForExaminer :many

SELECT id, title, status, question_count, started_at, ended_at, join_code, allow_any_examinee, created_at, creator_id, script_id FROM sessions
WHERE sessions.creator_id = $1::UUID
    AND ($2::TEXT = '' OR sessions.title ILIKE '%' || $2::TEXT || '%')
    AND (sessions.created_at, sessions.id) < ($3::TIMESTAMPTZ, $4::UUID)
    AND ($5::session_status IS NULL OR sessions.status = $5::session_status)
    ORDER BY sessions.created_at DESC, sessions.id DESC
LIMIT $6
`

type FindSessionsForExaminerParams struct {
	ExaminerID uuid.UUID         `json:"examiner_id"`
	Search     string            `json:"search"`
	CursorTs   time.Time         `json:"cursor_ts"`
	CursorID   uuid.UUID         `json:"cursor_id"`
	Status     NullSessionStatus `json:"status"`
	PageSize   int32             `json:"page_size"`
}

// Gets the sessions belonging to the examiner
// with cursor pagination and a search query
func (q *Queries) FindSessionsForExaminer(ctx context.Context, arg FindSessionsForExaminerParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, findSessionsForExaminer,
		arg.ExaminerID,
		arg.Search,
		arg.CursorTs,
		arg.CursorID,
		arg.Status,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.QuestionCount,
			&i.StartedAt,
			&i.EndedAt,
			&i.JoinCode,
			&i.AllowAnyExaminee,
			&i.CreatedAt,
			&i.CreatorID,
			&i.ScriptID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openSession = `-- name: OpenSession :one

UPDATE sessions SET
    status = 'open'
WHERE sessions.id = $1
    AND sessions.status = 'closed'
RETURNING id, title, status, question_count, started_at, ended_at, join_code, allow_any_examinee, created_at, creator_id, script_id
`

// Puts the session in OPEN mode. While in OPEN mode
// examinees can join the session. Only sessions in
// CLOSED mode can be opened.
func (q *Queries) OpenSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, openSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.QuestionCount,
		&i.StartedAt,
		&i.EndedAt,
		&i.JoinCode,
		&i.AllowAnyExaminee,
		&i.CreatedAt,
		&i.CreatorID,
		&i.ScriptID,
	)
	return i, err
}

const startSession = `-- name: StartSession :one

WITH updated_session AS (
    UPDATE sessions SET
        status      = 'started',
        started_at  = now()
    WHERE sessions.id = $1
        AND sessions.status = 'open'
    RETURNING id, title, status, question_count, started_at, ended_at, join_code, allow_any_examinee, created_at, creator_id, script_id
)
UPDATE scripts SET locked = true
FROM updated_session
WHERE scripts.id = updated_session.script_id
RETURNING updated_session.id, updated_session.title, updated_session.status, updated_session.question_count, updated_session.started_at, updated_session.ended_at, updated_session.join_code, updated_session.allow_any_examinee, updated_session.created_at, updated_session.creator_id, updated_session.script_id
`

type StartSessionRow struct {
	ID               uuid.UUID     `json:"id"`
	Title            string        `json:"title"`
	Status           SessionStatus `json:"status"`
	QuestionCount    *int32        `json:"question_count"`
	StartedAt        *time.Time    `json:"started_at"`
	EndedAt          *time.Time    `json:"ended_at"`
	JoinCode         string        `json:"join_code"`
	AllowAnyExaminee bool          `json:"allow_any_examinee"`
	CreatedAt        time.Time     `json:"created_at"`
	CreatorID        uuid.UUID     `json:"creator_id"`
	ScriptID         uuid.UUID     `json:"script_id"`
}

// Sets the session to STARTED mode. Only sessions in OPEN
// mode can be started.
func (q *Queries) StartSession(ctx context.Context, id uuid.UUID) (StartSessionRow, error) {
	row := q.db.QueryRow(ctx, startSession, id)
	var i StartSessionRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.QuestionCount,
		&i.StartedAt,
		&i.EndedAt,
		&i.JoinCode,
		&i.AllowAnyExaminee,
		&i.CreatedAt,
		&i.CreatorID,
		&i.ScriptID,
	)
	return i, err
}

const updateSessionFields = `-- name: UpdateSessionFields :one

UPDATE sessions SET
    title       = $2,
    script_id   = $3
WHERE sessions.id = $1
    AND sessions.status IN ('open', 'closed')
RETURNING id, title, status, question_count, started_at, ended_at, join_code, allow_any_examinee, created_at, creator_id, script_id
`

type UpdateSessionFieldsParams struct {
	ID       uuid.UUID `json:"id"`
	Title    string    `json:"title"`
	ScriptID uuid.UUID `json:"script_id"`
}

// Updates the top level fields of the sessions
func (q *Queries) UpdateSessionFields(ctx context.Context, arg UpdateSessionFieldsParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionFields, arg.ID, arg.Title, arg.ScriptID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.QuestionCount,
		&i.StartedAt,
		&i.EndedAt,
		&i.JoinCode,
		&i.AllowAnyExaminee,
		&i.CreatedAt,
		&i.CreatorID,
		&i.ScriptID,
	)
	return i, err
}
