// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const calculateSubmisionMark = `-- name: CalculateSubmisionMark :one

WITH total AS (
    SELECT sum(sq.mark) AS mark FROM submission_questions sq
    WHERE sq.submission_id = $1::uuid
) UPDATE submissions SET
    mark    = total.mark,
    status  = 'marked'
FROM total
WHERE submissions.id = $1::uuid
    AND submissions.status = 'submitted'
RETURNING total.mark
`

// Calculates the mark for a submission based on
// the individual marks for each question's answer.
//
// -------------------------------------------------
func (q *Queries) CalculateSubmisionMark(ctx context.Context, submissionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, calculateSubmisionMark, submissionID)
	var mark int64
	err := row.Scan(&mark)
	return mark, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (
    session_id, examinee_id
) VALUES ($1, $2) RETURNING id, mark, status, submitted_at, joined_at, examinee_id, session_id
`

type CreateSubmissionParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission, arg.SessionID, arg.ExamineeID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Mark,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const findSubmissionAnswers = `-- name: FindSubmissionAnswers :many

SELECT
    sq.question_id,
    coalesce(array_agg(answer_values.value) FILTER (WHERE answer_values.value IS NOT NULL), '{}')::text[] as value
FROM
    submissions INNER JOIN submission_questions sq ON sq.submission_id = submissions.id
    LEFT JOIN answer_values
        ON sq.question_id = answer_values.question_id
        AND sq.submission_id = answer_values.submission_id
WHERE submissions.id = $1
GROUP BY sq.question_id, sq.created_at
ORDER BY sq.created_at ASC
`

type FindSubmissionAnswersRow struct {
	QuestionID uuid.UUID `json:"question_id"`
	Value      []string  `json:"value"`
}

// Gets the answers for a submission
//
// ----------------------------------
func (q *Queries) FindSubmissionAnswers(ctx context.Context, id uuid.UUID) ([]FindSubmissionAnswersRow, error) {
	rows, err := q.db.Query(ctx, findSubmissionAnswers, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSubmissionAnswersRow{}
	for rows.Next() {
		var i FindSubmissionAnswersRow
		if err := rows.Scan(&i.QuestionID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSubmissionByID = `-- name: FindSubmissionByID :one
SELECT id, mark, status, submitted_at, joined_at, examinee_id, session_id FROM submissions WHERE submissions.id = $1
`

func (q *Queries) FindSubmissionByID(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, findSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Mark,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const findSubmissionsForSession = `-- name: FindSubmissionsForSession :many
SELECT id, mark, status, submitted_at, joined_at, examinee_id, session_id FROM submissions WHERE submissions.session_id = $1
`

func (q *Queries) FindSubmissionsForSession(ctx context.Context, sessionID uuid.UUID) ([]Submission, error) {
	rows, err := q.db.Query(ctx, findSubmissionsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.Mark,
			&i.Status,
			&i.SubmittedAt,
			&i.JoinedAt,
			&i.ExamineeID,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceSubAnswerForQuestion = `-- name: ReplaceSubAnswerForQuestion :exec

WITH deleted AS (
    DELETE FROM answer_values
    WHERE answer_values.submission_id = $1
        AND answer_values.question_id = $2
    RETURNING 1
) INSERT INTO answer_values (
    submission_id,
    question_id,
    value
) SELECT $1, $2, unnest($3::text[]) FROM
    submissions INNER JOIN sessions ON submissions.session_id = sessions.id
    CROSS JOIN (SELECT count(*) FROM deleted) AS _dep
WHERE submissions.id = $1
    AND submissions.status = 'editable'
    AND sessions.status = 'started'
`

type ReplaceSubAnswerForQuestionParams struct {
	SubmissionID uuid.UUID `json:"submission_id"`
	QuestionID   uuid.UUID `json:"question_id"`
	Value        []string  `json:"value"`
}

// Replaces the submission answer for a given question
//
// ----------------------------------------------------
func (q *Queries) ReplaceSubAnswerForQuestion(ctx context.Context, arg ReplaceSubAnswerForQuestionParams) error {
	_, err := q.db.Exec(ctx, replaceSubAnswerForQuestion, arg.SubmissionID, arg.QuestionID, arg.Value)
	return err
}

const setQuestionsForSubmissions = `-- name: SetQuestionsForSubmissions :exec

WITH selected AS (
    SELECT submissions.id as submission_id, questions.id as question_id FROM
        scripts INNER JOIN questions ON scripts.id = questions.script_id
        INNER JOIN sessions ON sessions.script_id = scripts.id
        INNER JOIN submissions ON submissions.session_id = sessions.id
    WHERE sessions.id = $1::uuid
    ORDER BY random()
) INSERT INTO submission_questions (
    submission_id,
    question_id
) SELECT selected.submission_id, selected.question_id FROM selected
`

// Sets the questions for the submission of a user. Intended to
// be used after an examiner starts the exam session before
// submissions are set as 'editable' for examinees to answer
//
// --------------------------------------------------------------
func (q *Queries) SetQuestionsForSubmissions(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setQuestionsForSubmissions, sessionID)
	return err
}

const setSubmissionQuestionMark = `-- name: SetSubmissionQuestionMark :one

UPDATE submission_questions SET
    mark = $3::integer
FROM submissions
WHERE submission_questions.submission_id = $1
    AND submission_questions.question_id = $2
    AND submissions.id = submission_questions.submission_id
    AND submissions.status = 'submitted'
RETURNING submission_questions.submission_id, submission_questions.question_id, submission_questions.mark, submission_questions.created_at
`

type SetSubmissionQuestionMarkParams struct {
	SubmissionID uuid.UUID `json:"submission_id"`
	QuestionID   uuid.UUID `json:"question_id"`
	Mark         int32     `json:"mark"`
}

// Updates the mark for an answer to a question in
// a submission. Can only update a submitted submission
//
// -----------------------------------------------------
func (q *Queries) SetSubmissionQuestionMark(ctx context.Context, arg SetSubmissionQuestionMarkParams) (SubmissionQuestion, error) {
	row := q.db.QueryRow(ctx, setSubmissionQuestionMark, arg.SubmissionID, arg.QuestionID, arg.Mark)
	var i SubmissionQuestion
	err := row.Scan(
		&i.SubmissionID,
		&i.QuestionID,
		&i.Mark,
		&i.CreatedAt,
	)
	return i, err
}

const setSubmissionsEditableForSession = `-- name: SetSubmissionsEditableForSession :exec

UPDATE submissions SET
    status = 'editable'
WHERE submissions.session_id = $1
`

// Set submissions as editable. Intended to be used
// when the session has been started and the questions
// for each user's submission has been set
//
// ----------------------------------------------------
func (q *Queries) SetSubmissionsEditableForSession(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setSubmissionsEditableForSession, sessionID)
	return err
}

const submitAllSubmissionsForSession = `-- name: SubmitAllSubmissionsForSession :exec

UPDATE submissions SET
    status          = 'submitted',
    submitted_at    = now()
WHERE submissions.session_id = $1
    AND submissions.status != 'submitted'
`

// Submits submission for a given session. Intended to be
// used by the server to auto lock examinee submissions
// when the session ends. Once submitted, the submission
// can not be edited again.
//
// -------------------------------------------------------
func (q *Queries) SubmitAllSubmissionsForSession(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, submitAllSubmissionsForSession, sessionID)
	return err
}

const submitSubmission = `-- name: SubmitSubmission :one

UPDATE submissions SET
    status          = 'submitted',
    submitted_at    = now()
WHERE submissions.examinee_id = $1
    AND submissions.session_id = $2
RETURNING id, mark, status, submitted_at, joined_at, examinee_id, session_id
`

type SubmitSubmissionParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Submits a single submission for an examinee. Intended to
// be used by the examinee to submit their answers when done
//
// ----------------------------------------------------------
func (q *Queries) SubmitSubmission(ctx context.Context, arg SubmitSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, submitSubmission, arg.ExamineeID, arg.SessionID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Mark,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}
