// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const autoMarkQuestion = `-- name: AutoMarkQuestion :one

WITH key_count AS (
    SELECT count(*) as value FROM answer_keys
    WHERE answer_keys.question_id = $2::uuid
)
UPDATE submission_questions sq SET
    mark = CASE
        WHEN $1::boolean = true THEN get_question_mark($2::uuid)
        ELSE 0
    END
FROM submissions s, key_count kc
WHERE
        s.id = sq.submission_id
    AND s.session_id = $3::uuid
    AND s.examinee_id = $4::uuid
    AND sq.question_id = $2::uuid

    -- [X] Mark must be NULL prior
    -- [X] Submission must have a SUBMITTED status
    -- [X] Answer Key count is greater than 0

    AND sq.mark IS NULL
    AND s.status = 'submitted'
    AND kc.value > 0

RETURNING sq.submission_id, sq.question_id, sq.mark, sq.feedback, sq.created_at
`

type AutoMarkQuestionParams struct {
	IsCorrect  bool      `json:"is_correct"`
	QuestionID uuid.UUID `json:"question_id"`
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

// Automatically gives a mark to the question. Will
// only give the mark as 0, or the maximum mark based
// on the application layer's is_correct value.
//
// If this fails for any of the questions, then the whole
// thing should fail, meaning that post marking of these
// questions,
func (q *Queries) AutoMarkQuestion(ctx context.Context, arg AutoMarkQuestionParams) (SubmissionQuestion, error) {
	row := q.db.QueryRow(ctx, autoMarkQuestion,
		arg.IsCorrect,
		arg.QuestionID,
		arg.SessionID,
		arg.ExamineeID,
	)
	var i SubmissionQuestion
	err := row.Scan(
		&i.SubmissionID,
		&i.QuestionID,
		&i.Mark,
		&i.Feedback,
		&i.CreatedAt,
	)
	return i, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (
    session_id, examinee_id
) VALUES ($1, $2) RETURNING id, status, submitted_at, joined_at, examinee_id, session_id
`

type CreateSubmissionParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission, arg.SessionID, arg.ExamineeID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const examineeFindSubmitted = `-- name: ExamineeFindSubmitted :many
SELECT id, status, submitted_at, joined_at, examinee_id, session_id FROM submissions s
WHERE s.examinee_id = $1
    AND s.status IN ('submitted', 'unreviewed', 'marked')
ORDER BY s.joined_at DESC
`

func (q *Queries) ExamineeFindSubmitted(ctx context.Context, examineeID uuid.UUID) ([]Submission, error) {
	rows, err := q.db.Query(ctx, examineeFindSubmitted, examineeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.SubmittedAt,
			&i.JoinedAt,
			&i.ExamineeID,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const examinerMarkQuestion = `-- name: ExaminerMarkQuestion :exec

WITH key_count AS (
    SELECT count(*) as value FROM answer_keys
    WHERE answer_keys.question_id = $2::uuid
)
UPDATE submission_questions sq SET
    mark        = greatest(0, least($1::integer, get_question_mark($2::uuid))),
    feedback    = $3::text
FROM submissions s, key_count kc
WHERE
        s.id = sq.submission_id
    AND s.session_id = $4::uuid
    AND s.examinee_id = $5::uuid
    AND sq.question_id = $2::uuid

    -- [X] Mark must be NULL prior
    -- [X] Submission must have an UNREVIEWED status
    -- [X] Answer Key count is equal to 0

    AND sq.mark IS NULL
    AND s.status = 'unreviewed'
    AND kc.value = 0

RETURNING sq.submission_id, sq.question_id, sq.mark, sq.feedback, sq.created_at
`

type ExaminerMarkQuestionParams struct {
	Mark       int32     `json:"mark"`
	QuestionID uuid.UUID `json:"question_id"`
	Feedback   string    `json:"feedback"`
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

// Sets the mark manually for an individual question.
// Should clamp the mark to (0, get_question_mark(question_id))
func (q *Queries) ExaminerMarkQuestion(ctx context.Context, arg ExaminerMarkQuestionParams) error {
	_, err := q.db.Exec(ctx, examinerMarkQuestion,
		arg.Mark,
		arg.QuestionID,
		arg.Feedback,
		arg.SessionID,
		arg.ExamineeID,
	)
	return err
}

const findSubmissionAnswers = `-- name: FindSubmissionAnswers :many

SELECT
    sq.submission_id, sq.question_id, sq.mark, sq.feedback, sq.created_at,
    coalesce(array_agg(answer_values.value) FILTER (WHERE answer_values.value IS NOT NULL), '{}')::text[] as value
FROM
    submissions s INNER JOIN submission_questions sq ON sq.submission_id = s.id
    LEFT JOIN answer_values
        ON sq.question_id = answer_values.question_id
        AND sq.submission_id = answer_values.submission_id
WHERE s.session_id = $1
    AND s.examinee_id = $2
GROUP BY sq.submission_id, sq.question_id, sq.created_at
ORDER BY sq.created_at ASC
`

type FindSubmissionAnswersParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

type FindSubmissionAnswersRow struct {
	SubmissionQuestion SubmissionQuestion `json:"submission_question"`
	Value              []string           `json:"value"`
}

// Gets the answers for a submission
func (q *Queries) FindSubmissionAnswers(ctx context.Context, arg FindSubmissionAnswersParams) ([]FindSubmissionAnswersRow, error) {
	rows, err := q.db.Query(ctx, findSubmissionAnswers, arg.SessionID, arg.ExamineeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSubmissionAnswersRow{}
	for rows.Next() {
		var i FindSubmissionAnswersRow
		if err := rows.Scan(
			&i.SubmissionQuestion.SubmissionID,
			&i.SubmissionQuestion.QuestionID,
			&i.SubmissionQuestion.Mark,
			&i.SubmissionQuestion.Feedback,
			&i.SubmissionQuestion.CreatedAt,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSubmissionByID = `-- name: FindSubmissionByID :one

SELECT id, status, submitted_at, joined_at, examinee_id, session_id FROM submissions s
WHERE s.session_id = $1::uuid
    AND s.examinee_id = $2::uuid
LIMIT 1
`

type FindSubmissionByIDParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

// Find submission with matching session ID and examinee ID.
func (q *Queries) FindSubmissionByID(ctx context.Context, arg FindSubmissionByIDParams) (Submission, error) {
	row := q.db.QueryRow(ctx, findSubmissionByID, arg.SessionID, arg.ExamineeID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const findSubmissionsForSession = `-- name: FindSubmissionsForSession :many
SELECT id, status, submitted_at, joined_at, examinee_id, session_id FROM submissions WHERE submissions.session_id = $1
`

func (q *Queries) FindSubmissionsForSession(ctx context.Context, sessionID uuid.UUID) ([]Submission, error) {
	rows, err := q.db.Query(ctx, findSubmissionsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.SubmittedAt,
			&i.JoinedAt,
			&i.ExamineeID,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSubmssionsForSessionWithUser = `-- name: FindSubmssionsForSessionWithUser :many

SELECT submissions.id, submissions.status, submissions.submitted_at, submissions.joined_at, submissions.examinee_id, submissions.session_id, users.id, users.email, users.first_name, users.last_name, users.password_hash, users.role FROM
    submissions INNER JOIN users ON submissions.examinee_id = users.id
WHERE submissions.session_id = $1
`

type FindSubmssionsForSessionWithUserRow struct {
	Submission Submission `json:"submission"`
	User       User       `json:"user"`
}

func (q *Queries) FindSubmssionsForSessionWithUser(ctx context.Context, sessionID uuid.UUID) ([]FindSubmssionsForSessionWithUserRow, error) {
	rows, err := q.db.Query(ctx, findSubmssionsForSessionWithUser, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSubmssionsForSessionWithUserRow{}
	for rows.Next() {
		var i FindSubmssionsForSessionWithUserRow
		if err := rows.Scan(
			&i.Submission.ID,
			&i.Submission.Status,
			&i.Submission.SubmittedAt,
			&i.Submission.JoinedAt,
			&i.Submission.ExamineeID,
			&i.Submission.SessionID,
			&i.User.ID,
			&i.User.Email,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.PasswordHash,
			&i.User.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionMark = `-- name: GetQuestionMark :one

SELECT get_question_mark($1::uuid)::integer
`

func (q *Queries) GetQuestionMark(ctx context.Context, questionID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getQuestionMark, questionID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const replaceAnswerForQuestion = `-- name: ReplaceAnswerForQuestion :exec

WITH deleted AS (
    DELETE FROM answer_values
    WHERE answer_values.submission_id = $1
        AND answer_values.question_id = $2
    RETURNING 1
)
INSERT INTO answer_values (
    submission_id,
    question_id,
    value
) SELECT $1, $2, unnest($3::text[]) FROM
    submissions INNER JOIN sessions ON submissions.session_id = sessions.id
    CROSS JOIN (SELECT count(*) FROM deleted) AS _dep
WHERE submissions.id = $1
    AND submissions.status = 'editable'
    AND sessions.status = 'started'
`

type ReplaceAnswerForQuestionParams struct {
	SubmissionID uuid.UUID `json:"submission_id"`
	QuestionID   uuid.UUID `json:"question_id"`
	Value        []string  `json:"value"`
}

// Replaces the submission answer for a given question
func (q *Queries) ReplaceAnswerForQuestion(ctx context.Context, arg ReplaceAnswerForQuestionParams) error {
	_, err := q.db.Exec(ctx, replaceAnswerForQuestion, arg.SubmissionID, arg.QuestionID, arg.Value)
	return err
}

const setQuestionsForSubmissions = `-- name: SetQuestionsForSubmissions :exec

WITH selected AS (
    SELECT submissions.id as submission_id, questions.id as question_id FROM
        scripts INNER JOIN questions ON scripts.id = questions.script_id
        INNER JOIN sessions ON sessions.script_id = scripts.id
        INNER JOIN submissions ON submissions.session_id = sessions.id
    WHERE sessions.id = $1::uuid
    ORDER BY random()
)
INSERT INTO submission_questions (
    submission_id,
    question_id
) SELECT selected.submission_id, selected.question_id FROM selected
`

// Sets the questions for the submission of a user. Intended to
// be used after an examiner starts the exam session before
// submissions are set as EDITABLE for examinees to answer
func (q *Queries) SetQuestionsForSubmissions(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setQuestionsForSubmissions, sessionID)
	return err
}

const submissionMarks = `-- name: SubmissionMarks :one
SELECT sum(sq.mark) as lhs, sum(get_question_mark(sq.question_id)) as rhs FROM
    submission_questions sq JOIN submissions s ON sq.submission_id = s.id
WHERE
        s.session_id = $1
    AND s.examinee_id = $2
    AND s.status = 'marked'
LIMIT 1
`

type SubmissionMarksParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

type SubmissionMarksRow struct {
	Lhs int64 `json:"lhs"`
	Rhs int64 `json:"rhs"`
}

func (q *Queries) SubmissionMarks(ctx context.Context, arg SubmissionMarksParams) (SubmissionMarksRow, error) {
	row := q.db.QueryRow(ctx, submissionMarks, arg.SessionID, arg.ExamineeID)
	var i SubmissionMarksRow
	err := row.Scan(&i.Lhs, &i.Rhs)
	return i, err
}
