// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions_status.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const findConnectableSubmission = `-- name: FindConnectableSubmission :one

SELECT submissions.id FROM
    submissions INNER JOIN sessions on submissions.session_id = sessions.id
WHERE submissions.session_id = $1
    AND submissions.examinee_id = $2
    AND (
        (sessions.status = 'open' AND submissions.status IN ('enrolled', 'left'))
        OR (sessions.status = 'started' AND submissions.status = 'disconnected')
    )
`

type FindConnectableSubmissionParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

// Returns the submission ID if the examinee may open a websocket connection.
//
// OPEN:     enrolled or left (waiting room entry / reconnect)
// STARTED:  disconnected only (grace reconnect; flagged requires appeal first)
func (q *Queries) FindConnectableSubmission(ctx context.Context, arg FindConnectableSubmissionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findConnectableSubmission, arg.SessionID, arg.ExamineeID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findSubmissionStatus = `-- name: FindSubmissionStatus :one

SELECT submissions.status FROM submissions
WHERE submissions.session_id = $1
    AND submissions.examinee_id = $2
`

type FindSubmissionStatusParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

func (q *Queries) FindSubmissionStatus(ctx context.Context, arg FindSubmissionStatusParams) (SubmissionStatus, error) {
	row := q.db.QueryRow(ctx, findSubmissionStatus, arg.SessionID, arg.ExamineeID)
	var status SubmissionStatus
	err := row.Scan(&status)
	return status, err
}

const setSubmissionDisconnected = `-- name: SetSubmissionDisconnected :one

UPDATE submissions SET
    status = 'disconnected'
WHERE submissions.examinee_id = $1
    AND submissions.session_id = $2
    AND submissions.status IN ('editable')
RETURNING id, mark, status, submitted_at, joined_at, examinee_id, session_id
`

type SetSubmissionDisconnectedParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Disconnect during STARTED while still eligible to answer (EDITABLE -> DISCONNECTED).
func (q *Queries) SetSubmissionDisconnected(ctx context.Context, arg SetSubmissionDisconnectedParams) (Submission, error) {
	row := q.db.QueryRow(ctx, setSubmissionDisconnected, arg.ExamineeID, arg.SessionID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Mark,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setSubmissionDisconnectedFromFlagged = `-- name: SetSubmissionDisconnectedFromFlagged :one

UPDATE submissions SET
    status = 'disconnected'
WHERE submissions.examinee_id = $1
    AND submissions.session_id = $2
    AND submissions.status = 'flagged'
RETURNING id, mark, status, submitted_at, joined_at, examinee_id, session_id
`

type SetSubmissionDisconnectedFromFlaggedParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Examiner grants appeal and client is disconnected in
// session hub (FLAGGED -> DISCONNECTED).
func (q *Queries) SetSubmissionDisconnectedFromFlagged(ctx context.Context, arg SetSubmissionDisconnectedFromFlaggedParams) (Submission, error) {
	row := q.db.QueryRow(ctx, setSubmissionDisconnectedFromFlagged, arg.ExamineeID, arg.SessionID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Mark,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setSubmissionDisconnectedFromLeft = `-- name: SetSubmissionDisconnectedFromLeft :one

UPDATE submissions SET
    status = 'disconnected'
WHERE submissions.examinee_id = $1
AND submissions.session_id = $2
AND submissions.status = 'left'
RETURNING id, mark, status, submitted_at, joined_at, examinee_id, session_id
`

type SetSubmissionDisconnectedFromLeftParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Examiner readmit after missing the start window (LEFT -> DISCONNECTED).
// Examinee reconnects with SetSubmissionEditableFromDisconnect.
func (q *Queries) SetSubmissionDisconnectedFromLeft(ctx context.Context, arg SetSubmissionDisconnectedFromLeftParams) (Submission, error) {
	row := q.db.QueryRow(ctx, setSubmissionDisconnectedFromLeft, arg.ExamineeID, arg.SessionID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Mark,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setSubmissionEditableFromDisconnect = `-- name: SetSubmissionEditableFromDisconnect :one

UPDATE submissions SET
    status = 'editable'
WHERE submissions.examinee_id = $1
    AND submissions.session_id = $2
    AND submissions.status = 'disconnected'
RETURNING id, mark, status, submitted_at, joined_at, examinee_id, session_id
`

type SetSubmissionEditableFromDisconnectParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Reconnect during STARTED after grace disconnect (DISCONNECTED -> EDITABLE).
func (q *Queries) SetSubmissionEditableFromDisconnect(ctx context.Context, arg SetSubmissionEditableFromDisconnectParams) (Submission, error) {
	row := q.db.QueryRow(ctx, setSubmissionEditableFromDisconnect, arg.ExamineeID, arg.SessionID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Mark,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setSubmissionEditableFromFlagged = `-- name: SetSubmissionEditableFromFlagged :one

UPDATE submissions SET
    status = 'editable'
WHERE submissions.examinee_id = $1
    AND submissions.session_id = $2
    AND submissions.status = 'flagged'
RETURNING id, mark, status, submitted_at, joined_at, examinee_id, session_id
`

type SetSubmissionEditableFromFlaggedParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Examiner grants appeal and client is connected in session
// hub (FLAGGED -> EDITABLE).
func (q *Queries) SetSubmissionEditableFromFlagged(ctx context.Context, arg SetSubmissionEditableFromFlaggedParams) (Submission, error) {
	row := q.db.QueryRow(ctx, setSubmissionEditableFromFlagged, arg.ExamineeID, arg.SessionID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Mark,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setSubmissionFlaggedFromDisconnect = `-- name: SetSubmissionFlaggedFromDisconnect :one

UPDATE submissions SET
    status = 'flagged'
WHERE submissions.examinee_id = $1
    AND submissions.session_id = $2
    AND submissions.status = 'disconnected'
RETURNING id, mark, status, submitted_at, joined_at, examinee_id, session_id
`

type SetSubmissionFlaggedFromDisconnectParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Flag submission when grace period has expired
// (DISCONNECTED -> FLAGGED).
func (q *Queries) SetSubmissionFlaggedFromDisconnect(ctx context.Context, arg SetSubmissionFlaggedFromDisconnectParams) (Submission, error) {
	row := q.db.QueryRow(ctx, setSubmissionFlaggedFromDisconnect, arg.ExamineeID, arg.SessionID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Mark,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setSubmissionFlaggedFromEditable = `-- name: SetSubmissionFlaggedFromEditable :one

UPDATE submissions SET
    status = 'flagged'
WHERE submissions.examinee_id = $1
    AND submissions.session_id = $2
    AND submissions.status = 'editable'
RETURNING id, mark, status, submitted_at, joined_at, examinee_id, session_id
`

type SetSubmissionFlaggedFromEditableParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Flag submission when if server flags user as cheating
// (EDITABLE -> FLAGGED).
func (q *Queries) SetSubmissionFlaggedFromEditable(ctx context.Context, arg SetSubmissionFlaggedFromEditableParams) (Submission, error) {
	row := q.db.QueryRow(ctx, setSubmissionFlaggedFromEditable, arg.ExamineeID, arg.SessionID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Mark,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setSubmissionJoined = `-- name: SetSubmissionJoined :one

UPDATE submissions SET
    status = 'joined'
WHERE submissions.examinee_id = $1
    AND submissions.session_id = $2
    AND submissions.status IN ('enrolled', 'left')
RETURNING id, mark, status, submitted_at, joined_at, examinee_id, session_id
`

type SetSubmissionJoinedParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Connect during OPEN: first entry (ENROLLED -> JOINED)
// or reconnect (LEFT -> JOINED).
func (q *Queries) SetSubmissionJoined(ctx context.Context, arg SetSubmissionJoinedParams) (Submission, error) {
	row := q.db.QueryRow(ctx, setSubmissionJoined, arg.ExamineeID, arg.SessionID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Mark,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setSubmissionLeft = `-- name: SetSubmissionLeft :one

UPDATE submissions SET
    status = 'left'
WHERE submissions.examinee_id = $1
    AND submissions.session_id = $2
    AND submissions.status = 'joined'
RETURNING id, mark, status, submitted_at, joined_at, examinee_id, session_id
`

type SetSubmissionLeftParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Disconnect during OPEN (JOINED -> LEFT). Ensures session start does not
// promote disconnected examinees to EDITABLE.
func (q *Queries) SetSubmissionLeft(ctx context.Context, arg SetSubmissionLeftParams) (Submission, error) {
	row := q.db.QueryRow(ctx, setSubmissionLeft, arg.ExamineeID, arg.SessionID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Mark,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setSubmissionOnConnect = `-- name: SetSubmissionOnConnect :one

UPDATE submissions SET
    status = CASE
        WHEN sessions.status = 'open' THEN 'joined'::submission_status
        WHEN sessions.status = 'started' THEN 'editable'::submission_status
    END
FROM sessions
WHERE submissions.session_id = sessions.id
    AND submissions.session_id = $1
    AND submissions.examinee_id = $2
    AND (
        (sessions.status = 'open' AND submissions.status IN ('enrolled', 'left'))
        OR (sessions.status = 'started' AND submissions.status = 'disconnected')
    )
RETURNING submissions.id, submissions.mark, submissions.status, submissions.submitted_at, submissions.joined_at, submissions.examinee_id, submissions.session_id
`

type SetSubmissionOnConnectParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

// Set the submission status to a connected state based on current
// submission and session state
//
// submission: (ENROLLED, LEFT) session: OPEN       -> JOINED
// submission: (DISCONNECTED)   sesssion: STARTED   -> EDITABLE
func (q *Queries) SetSubmissionOnConnect(ctx context.Context, arg SetSubmissionOnConnectParams) (Submission, error) {
	row := q.db.QueryRow(ctx, setSubmissionOnConnect, arg.SessionID, arg.ExamineeID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Mark,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setSubmissionOnDisconnect = `-- name: SetSubmissionOnDisconnect :one

UPDATE submissions SET
    status = CASE
        WHEN sessions.status = 'open' THEN 'left'::submission_status
        WHEN sessions.status = 'started' THEN 'disconnected'::submission_status
    END
FROM sessions
WHERE submissions.session_id = sessions.id
    AND submissions.session_id = $1
    AND submissions.examinee_id = $2
    AND (
        (sessions.status = 'open' AND submissions.status = 'joined')
        OR (sessions.status = 'started' AND submissions.status = 'editable')
    )
RETURNING submissions.id, submissions.mark, submissions.status, submissions.submitted_at, submissions.joined_at, submissions.examinee_id, submissions.session_id
`

type SetSubmissionOnDisconnectParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

// Set the submission status to a disconnected state based
// on current submission and session state
//
// submission: (JOINED)     session: OPEN       -> LEFT
// submission: (EDITABLE)   sesssion: STARTED   -> DISCONNECTED
func (q *Queries) SetSubmissionOnDisconnect(ctx context.Context, arg SetSubmissionOnDisconnectParams) (Submission, error) {
	row := q.db.QueryRow(ctx, setSubmissionOnDisconnect, arg.SessionID, arg.ExamineeID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Mark,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const setSubmissionStatusesForStartedSession = `-- name: SetSubmissionStatusesForStartedSession :execrows

WITH enrolled_to_left AS (
    UPDATE submissions SET
        status = 'left'
    WHERE submissions.session_id = $1
        AND submissions.status = 'enrolled'
    RETURNING id
)
UPDATE submissions SET
    status = 'editable'
WHERE submissions.session_id = $1
    AND submissions.status = 'joined'
`

// On session start: promote waiting-room examinees and lock out no-shows.
// Use after the session is STARTED and submission questions are assigned.
//
// ENROLLED -> LEFT: enrolled but never connected during OPEN (see SetSubmissionJoined).
// JOINED -> EDITABLE: was in the waiting room when the exam started.
//
// Rows already LEFT (disconnected during OPEN) are unchanged and require
// examiner readmit (SetSubmissionDisconnectedFromLeft) to participate.
func (q *Queries) SetSubmissionStatusesForStartedSession(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, setSubmissionStatusesForStartedSession, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSubmissionSubmitted = `-- name: SetSubmissionSubmitted :one

UPDATE submissions SET
    status          = 'submitted',
    submitted_at    = now()
WHERE submissions.examinee_id = $1
    AND submissions.session_id = $2
    AND submissions.status = 'editable'
RETURNING id, mark, status, submitted_at, joined_at, examinee_id, session_id
`

type SetSubmissionSubmittedParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

// Voluntary final submit by the examinee (EDITABLE -> SUBMITTED).
func (q *Queries) SetSubmissionSubmitted(ctx context.Context, arg SetSubmissionSubmittedParams) (Submission, error) {
	row := q.db.QueryRow(ctx, setSubmissionSubmitted, arg.ExamineeID, arg.SessionID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Mark,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const submitAllSubmissionsForSession = `-- name: SubmitAllSubmissionsForSession :execrows

UPDATE submissions SET
    status          = 'submitted',
    submitted_at    = now()
WHERE submissions.session_id = $1
    AND submissions.status NOT IN ('submitted', 'marked', 'joined', 'enrolled')
`

// On session end: auto-submit all in-progress submissions for the session.
// Updates LEFT, EDITABLE, DISCONNECTED, and FLAGGED to SUBMITTED.
//
// ENROLLED and JOINED are excluded (should not exist after session start;
// see SetSubmissionStatusesForStartedSession). SUBMITTED and MARKED are terminal.
func (q *Queries) SubmitAllSubmissionsForSession(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, submitAllSubmissionsForSession, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
