// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createAnswerValue = `-- name: CreateAnswerValue :exec
INSERT INTO answer_values (
    submission_id, question_id, value
) VALUES ($1, $2, $3) RETURNING value
`

type CreateAnswerValueParams struct {
	SubmissionID uuid.UUID `json:"submission_id"`
	QuestionID   uuid.UUID `json:"question_id"`
	Value        string    `json:"value"`
}

func (q *Queries) CreateAnswerValue(ctx context.Context, arg CreateAnswerValueParams) error {
	_, err := q.db.Exec(ctx, createAnswerValue, arg.SubmissionID, arg.QuestionID, arg.Value)
	return err
}

type CreateAnswerValuesParams struct {
	SubmissionID uuid.UUID `json:"submission_id"`
	QuestionID   uuid.UUID `json:"question_id"`
	Value        string    `json:"value"`
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (
    session_id, examinee_id
) VALUES ($1, $2) RETURNING id, grade, status, submitted_at, joined_at, examinee_id, session_id
`

type CreateSubmissionParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission, arg.SessionID, arg.ExamineeID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Grade,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const deleteAnswerValuesByIDs = `-- name: DeleteAnswerValuesByIDs :execrows
DELETE FROM answer_values
    WHERE answer_values.submission_id = $1 AND answer_values.question_id = $2
`

type DeleteAnswerValuesByIDsParams struct {
	SubmissionID uuid.UUID `json:"submission_id"`
	QuestionID   uuid.UUID `json:"question_id"`
}

func (q *Queries) DeleteAnswerValuesByIDs(ctx context.Context, arg DeleteAnswerValuesByIDsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnswerValuesByIDs, arg.SubmissionID, arg.QuestionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findActiveSubmissionForScript = `-- name: FindActiveSubmissionForScript :one
SELECT submissions.id, submissions.grade, submissions.status, submissions.submitted_at, submissions.joined_at, submissions.examinee_id, submissions.session_id FROM
    submissions INNER JOIN sessions ON submissions.session_id = sessions.id
    INNER JOIN scripts ON sessions.script_id = scripts.id
WHERE scripts.id = $1
    AND submissions.examinee_id = $2
    AND submissions.status = 'editable'
    AND sessions.status = 'started'
`

type FindActiveSubmissionForScriptParams struct {
	ID         uuid.UUID `json:"id"`
	ExamineeID uuid.UUID `json:"examinee_id"`
}

func (q *Queries) FindActiveSubmissionForScript(ctx context.Context, arg FindActiveSubmissionForScriptParams) (Submission, error) {
	row := q.db.QueryRow(ctx, findActiveSubmissionForScript, arg.ID, arg.ExamineeID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Grade,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const findAnswerValuesForQuestion = `-- name: FindAnswerValuesForQuestion :many
SELECT answer_values.value FROM answer_values
    WHERE answer_values.submission_id = $1 AND question_id = $2
`

type FindAnswerValuesForQuestionParams struct {
	SubmissionID uuid.UUID `json:"submission_id"`
	QuestionID   uuid.UUID `json:"question_id"`
}

func (q *Queries) FindAnswerValuesForQuestion(ctx context.Context, arg FindAnswerValuesForQuestionParams) ([]string, error) {
	rows, err := q.db.Query(ctx, findAnswerValuesForQuestion, arg.SubmissionID, arg.QuestionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var value string
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAnswersForSubmission = `-- name: FindAnswersForSubmission :many
SELECT answers.submission_id, answers.question_id, answers.grade FROM answers
    WHERE answers.submission_id = $1
`

func (q *Queries) FindAnswersForSubmission(ctx context.Context, submissionID uuid.UUID) ([]Answer, error) {
	rows, err := q.db.Query(ctx, findAnswersForSubmission, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Answer{}
	for rows.Next() {
		var i Answer
		if err := rows.Scan(&i.SubmissionID, &i.QuestionID, &i.Grade); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSubmissionByExamineeAndSession = `-- name: FindSubmissionByExamineeAndSession :one
SELECT id, grade, status, submitted_at, joined_at, examinee_id, session_id FROM submissions
WHERE submissions.examinee_id = $1
    AND submissions.session_id = $2
LIMIT 1
`

type FindSubmissionByExamineeAndSessionParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

func (q *Queries) FindSubmissionByExamineeAndSession(ctx context.Context, arg FindSubmissionByExamineeAndSessionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, findSubmissionByExamineeAndSession, arg.ExamineeID, arg.SessionID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Grade,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const findSubmissionByID = `-- name: FindSubmissionByID :one
SELECT id, grade, status, submitted_at, joined_at, examinee_id, session_id FROM submissions WHERE submissions.id = $1
`

func (q *Queries) FindSubmissionByID(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, findSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Grade,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const findSubmissionsForExaminee = `-- name: FindSubmissionsForExaminee :many
SELECT id, grade, status, submitted_at, joined_at, examinee_id, session_id FROM submissions WHERE submissions.examinee_id = $1
`

func (q *Queries) FindSubmissionsForExaminee(ctx context.Context, examineeID uuid.UUID) ([]Submission, error) {
	rows, err := q.db.Query(ctx, findSubmissionsForExaminee, examineeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.Grade,
			&i.Status,
			&i.SubmittedAt,
			&i.JoinedAt,
			&i.ExamineeID,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSubmissionsForSession = `-- name: FindSubmissionsForSession :many
SELECT id, grade, status, submitted_at, joined_at, examinee_id, session_id FROM submissions WHERE submissions.session_id = $1
`

func (q *Queries) FindSubmissionsForSession(ctx context.Context, sessionID uuid.UUID) ([]Submission, error) {
	rows, err := q.db.Query(ctx, findSubmissionsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.Grade,
			&i.Status,
			&i.SubmittedAt,
			&i.JoinedAt,
			&i.ExamineeID,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSubmissionsEditableForSession = `-- name: SetSubmissionsEditableForSession :exec
UPDATE submissions SET
    status = 'editable'
WHERE submissions.session_id = $1
`

func (q *Queries) SetSubmissionsEditableForSession(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setSubmissionsEditableForSession, sessionID)
	return err
}

const submitSubmission = `-- name: SubmitSubmission :one
UPDATE submissions SET
    status          = 'submitted',
    submitted_at    = now()
WHERE submissions.examinee_id = $1
    AND submissions.session_id = $2
RETURNING id, grade, status, submitted_at, joined_at, examinee_id, session_id
`

type SubmitSubmissionParams struct {
	ExamineeID uuid.UUID `json:"examinee_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

func (q *Queries) SubmitSubmission(ctx context.Context, arg SubmitSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, submitSubmission, arg.ExamineeID, arg.SessionID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Grade,
		&i.Status,
		&i.SubmittedAt,
		&i.JoinedAt,
		&i.ExamineeID,
		&i.SessionID,
	)
	return i, err
}

const submitSubmissionsForSession = `-- name: SubmitSubmissionsForSession :exec
UPDATE submissions SET
    status          = 'submitted',
    submitted_at    = now()
WHERE submissions.session_id = $1
`

func (q *Queries) SubmitSubmissionsForSession(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, submitSubmissionsForSession, sessionID)
	return err
}

const updateSubmissionGrade = `-- name: UpdateSubmissionGrade :exec
UPDATE submissions SET grade = $2
    WHERE submissions.id = $1
`

type UpdateSubmissionGradeParams struct {
	ID    uuid.UUID `json:"id"`
	Grade *int32    `json:"grade"`
}

func (q *Queries) UpdateSubmissionGrade(ctx context.Context, arg UpdateSubmissionGradeParams) error {
	_, err := q.db.Exec(ctx, updateSubmissionGrade, arg.ID, arg.Grade)
	return err
}
