// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createExaminee = `-- name: CreateExaminee :one
INSERT INTO examinees (id) VALUES ($1) RETURNING id
`

func (q *Queries) CreateExaminee(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createExaminee, id)
	err := row.Scan(&id)
	return id, err
}

const createExaminer = `-- name: CreateExaminer :one
INSERT INTO examiners (id) VALUES ($1) RETURNING id
`

func (q *Queries) CreateExaminer(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createExaminer, id)
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    first_name, last_name, email, password_hash, role
) VALUES ($1, $2, $3, $4, $5) RETURNING id, email, first_name, last_name, password_hash, role
`

type CreateUserParams struct {
	FirstName    string   `json:"first_name"`
	LastName     string   `json:"last_name"`
	Email        string   `json:"email"`
	PasswordHash string   `json:"-"`
	Role         UserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const findExamineeByEmail = `-- name: FindExamineeByEmail :one
SELECT users.id, users.email, users.first_name, users.last_name, users.password_hash, users.role FROM
    users INNER JOIN examinees ON users.id = examinees.id
WHERE email = $1 LIMIT 1
`

func (q *Queries) FindExamineeByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findExamineeByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const findExaminerByEmail = `-- name: FindExaminerByEmail :one
SELECT users.id, users.email, users.first_name, users.last_name, users.password_hash, users.role FROM
    users INNER JOIN examiners ON users.id = examiners.id
WHERE email = $1 LIMIT 1
`

func (q *Queries) FindExaminerByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findExaminerByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, first_name, last_name, password_hash, role FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, first_name, last_name, password_hash, role FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}
