// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createExaminee = `-- name: CreateExaminee :one

WITH
inserted_user AS (
    INSERT INTO users (
        first_name,
        last_name,
        email,
        password_hash,
        role
    ) VALUES ($1, $2, $3, $4, 'examinee')
    RETURNING id, email, first_name, last_name, password_hash, role
),
inserted_examinee AS (
    INSERT INTO examinees (id)
    SELECT inserted_user.id FROM inserted_user
    RETURNING id, role
)
SELECT inserted_user.id, inserted_user.email, inserted_user.first_name, inserted_user.last_name, inserted_user.password_hash, inserted_user.role FROM inserted_user
`

type CreateExamineeParams struct {
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	Email        string `json:"email"`
	PasswordHash string `json:"-"`
}

type CreateExamineeRow struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	PasswordHash string    `json:"password_hash"`
	Role         UserRole  `json:"role"`
}

// Creates a new examinee. Intended to be used by students
// to partake in examinations. In the future, ensure email
// is linked to valid domains e.g. bazeuniversity.edu.ng
func (q *Queries) CreateExaminee(ctx context.Context, arg CreateExamineeParams) (CreateExamineeRow, error) {
	row := q.db.QueryRow(ctx, createExaminee,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
	)
	var i CreateExamineeRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const createExaminer = `-- name: CreateExaminer :one

WITH
inserted_user AS (
    INSERT INTO users (
        first_name,
        last_name,
        email,
        password_hash,
        role
    ) VALUES ($1, $2, $3, $4, 'examiner')
    RETURNING id, email, first_name, last_name, password_hash, role
),
inserted_examiner AS (
    INSERT INTO examiners (id)
    SELECT inserted_user.id FROM inserted_user
    RETURNING id, role
)
SELECT inserted_user.id, inserted_user.email, inserted_user.first_name, inserted_user.last_name, inserted_user.password_hash, inserted_user.role FROM inserted_user
`

type CreateExaminerParams struct {
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	Email        string `json:"email"`
	PasswordHash string `json:"-"`
}

type CreateExaminerRow struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	PasswordHash string    `json:"password_hash"`
	Role         UserRole  `json:"role"`
}

// Creates new examiner. Intended to be used by administrators
// to create user profiles for examiners (e.g. lecturers etc.).
// In the future, ensure email is linked to valid domains e.g.
// bazeuniversity.edu.ng
func (q *Queries) CreateExaminer(ctx context.Context, arg CreateExaminerParams) (CreateExaminerRow, error) {
	row := q.db.QueryRow(ctx, createExaminer,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
	)
	var i CreateExaminerRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const findExamineeByEmail = `-- name: FindExamineeByEmail :one
SELECT users.id, users.email, users.first_name, users.last_name, users.password_hash, users.role FROM
    users INNER JOIN examinees ON users.id = examinees.id
WHERE email = $1 LIMIT 1
`

func (q *Queries) FindExamineeByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findExamineeByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const findExaminerByEmail = `-- name: FindExaminerByEmail :one
SELECT users.id, users.email, users.first_name, users.last_name, users.password_hash, users.role FROM
    users INNER JOIN examiners ON users.id = examiners.id
WHERE email = $1 LIMIT 1
`

func (q *Queries) FindExaminerByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findExaminerByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, first_name, last_name, password_hash, role FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, first_name, last_name, password_hash, role FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}
