DROP TABLE IF EXISTS answer_values;
DROP TABLE IF EXISTS submission_questions CASCADE;
DROP TABLE IF EXISTS submissions CASCADE;

DROP TABLE IF EXISTS proctor_events;
DROP TABLE IF EXISTS proctor_event_types;
DROP TABLE IF EXISTS sessions CASCADE;

DROP TABLE IF EXISTS text_questions;
DROP TABLE IF EXISTS options;
DROP TABLE IF EXISTS choice_questions;
DROP TABLE IF EXISTS answer_keys;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS scripts CASCADE;

DROP TABLE IF EXISTS examiners;
DROP TABLE IF EXISTS examinees;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS user_role;
DROP TYPE IF EXISTS question_type;
DROP TYPE IF EXISTS session_status;
DROP TYPE IF EXISTS submission_status;
